'use strict';
/* Teewald City — textos em português e inglês */
(function () {
  var L = {};

  L.pt = {
    'boot.press': 'PRESSIONE START',
    'boot.hint': 'ENTER / Z / TOQUE',
    'boot.lang': 'ESCOLHA O IDIOMA',

    'menu.new': 'NOVO JOGO',
    'menu.continue': 'CONTINUAR',
    'menu.options': 'OPÇÕES',
    'menu.controls': 'CONTROLES',
    'title.sub': 'CAPÍTULO 1 — A CIDADE ADORMECIDA',
    'title.copy': '© 2026  TEEWALD CITY',

    'opt.title': 'OPÇÕES',
    'opt.lang': 'IDIOMA',
    'opt.crt': 'FILTRO CRT',
    'opt.chroma': 'ABERRAÇÃO CROMÁTICA',
    'opt.aspect': 'PROPORÇÃO',
    'opt.music': 'MÚSICA',
    'opt.sfx': 'EFEITOS',
    'opt.full': 'TELA CHEIA',
    'opt.back': 'VOLTAR',
    'on': 'LIGADO',
    'off': 'DESLIGADO',
    'aspect.square': 'PIXEL QUADRADO',
    'aspect.tv': 'TV 4:3',
    'lang.name': 'PORTUGUÊS',

    'ctrl.title': 'CONTROLES',
    'ctrl.move': 'MOVER',
    'ctrl.jump': 'PULAR',
    'ctrl.attack': 'ATACAR / COMBO',
    'ctrl.special': 'GIRO ESPECIAL',
    'ctrl.pause': 'PAUSA',
    'ctrl.read': 'LER PLACAS',
    'ctrl.keys1': 'SETAS / WASD',
    'ctrl.keys2': 'Z / ESPAÇO / K',
    'ctrl.keys3': 'X / J',
    'ctrl.keys4': 'C / L',
    'ctrl.keys5': 'ENTER / ESC',
    'ctrl.keys6': '↑ PERTO DA PLACA',
    'ctrl.pad': 'Controles USB e telas de toque também funcionam.',

    'pause': 'PAUSA',
    'pause.resume': 'CONTINUAR',
    'pause.quit': 'SAIR PARA O TÍTULO',

    'hud.score': 'PONTOS',
    'go': 'SIGA',
    'fight': 'LUTE!',
    'stage1.num': 'FASE 1',
    'stage1.name': 'A CIDADE ADORMECIDA',
    'continue': 'CONTINUAR?',
    'gameover': 'FIM DE JOGO',
    'clear': 'FASE CONCLUÍDA',
    'tally.score': 'PONTOS',
    'tally.time': 'BÔNUS DE TEMPO',
    'tally.hp': 'BÔNUS DE ENERGIA',
    'tally.total': 'TOTAL',
    'checkpoint': 'VELA ACESA',

    'hint.move': '◀ ▶ ANDAR    Z PULAR    X ATACAR',
    'hint.combo': 'X X X  =  COMBO!   PULO + X  =  VOADORA',
    'hint.special': 'C  =  GIRO ESPECIAL (gasta um pouco de energia)',
    'hint.break': 'Quebre caixotes e barris: tem comida dentro!',
    'hint.read': '↑  LER',

    'item.cuca': 'CUCA',
    'item.linguica': 'LINGUIÇA',
    'item.chimarrao': 'CHIMARRÃO',
    'item.pinhao': 'PINHÃO',
    'item.medalha': 'MEDALHA DE SÃO CRISTÓVÃO',
    'item.1up': '1 VIDA!',

    'en.ghost': 'ASSOMBRAÇÃO',
    'en.flame': 'CABEÇA-DE-FOGO',
    'en.shadow': 'VULTO',
    'en.crow': 'CORVO',
    'en.crate': 'CAIXOTE',
    'en.barrel': 'BARRIL',
    'boss.name': 'O CICLOPE GIGANTE',

    'name.arno': 'ARNO',
    'name.radio': 'RÁDIO',
    'name.voice': '???',
    'name.frida': 'DONA FRIDA',

    'intro.skip': 'START: PULAR',
    'intro.place': 'Sul do Brasil',
    'intro.date': 'Outono de 1997',
    'intro.road': 'Rodovia da Serra — 23h47',
    'intro.d1': 'Teewald City... Faz vinte anos que eu não subo essa serra.',
    'intro.d2': 'Meu pai fazia essa rota toda semana. E eu ia junto, guri ainda, no banco do carona.',
    'intro.d3': 'Olha essas araucárias... Tem umas aí que já eram velhas antes do primeiro colono chegar.',
    'intro.d4': 'Em noite de lua cheia, a cidade brilhava lá embaixo. As casas de enxaimel, a torre da igreja...',
    'intro.d5': 'Cheiro de batata assada, a Festa da Batata, a bandinha tocando na praça... Era a cidade mais bonita do mundo.',
    'intro.r1': '...ksshh... atenção, motoristas... kssh... neblina densa na serra...',
    'intro.r2': '...kshh... não... NÃO entrem em Teewald... kssshhh...',
    'intro.d6': 'Hã? ...Rádio velho. Nessa serra só pega chiado.',
    'intro.d7': 'Que neblina é essa, meu Deus... Não enxergo um palmo na frente.',
    'intro.d8': 'Calma, Arno. Devagar. Já tá chegando...',

    'wake.1': '...Hã...?',
    'wake.2': 'Ai... minha cabeça...',
    'wake.3': 'Cadê o caminhão? Eu tava descendo a serra... e agora...',
    'wake.4': 'Essas casas de enxaimel... a torre da igreja... É Teewald City. Tá igualzinha a como eu lembrava.',
    'wake.5': 'Mas cadê todo mundo? Nenhuma janela acesa... nenhum cachorro latindo...',
    'wake.6': '...Mas o que diabos é aquilo?!',

    'mid.bridge': 'O arroio... Meu pai me ensinou a pescar aqui embaixo.',
    'mid.cemetery': 'O cemitério da colônia... Velas acesas? Quem acendeu essas velas?',
    'mid.square': 'A praça da igreja. O sino... Tem alguém lá dentro?',

    'sign.welcome': 'BEM-VINDO A TEEWALD CITY\nFundada em 1852 por colonos do Reno.\n"Willkommen!"',
    'sign.festa': 'FESTA DA BATATA — 25ª EDIÇÃO\nBaile, bandinha e a Rainha da Batata.\nJunho de 1977.',
    'sign.missing': 'DESAPARECIDOS DESDE A NEBLINA:\nfamílias Schmitt, Kessler, Weber...\n(o resto do papel está rasgado)',
    'sign.bridge': 'PONTE DO ARROIO\nCuidado: tábuas soltas.',
    'sign.cemetery': 'CEMITÉRIO DA COLÔNIA\n"Aqui descansam os que vieram de longe."',
    'sign.bakery': 'PADARIA WEBER\nCuca de uva, de banana e de farofa.\nFechado.',

    'boss.1': 'Mas que bicho é esse...?!',
    'boss.2': 'Tá bom, feioso. Vem!',

    'end.1': 'Acabou...?',
    'end.2': 'Arno... Arno Becker.',
    'end.3': 'Quem tá aí? Como sabe o meu nome?',
    'end.4': 'Eu te benzi quando tu era guri. Tu tinha medo do escuro, lembra?',
    'end.5': '...Dona Frida? A benzedeira? Mas a senhora...',
    'end.6': 'Faz vinte anos que a noite não acaba em Teewald. Eles vieram com a neblina.',
    'end.7': 'E a cidade esperou. Esperou alguém que tivesse coragem de voltar.',
    'end.8': 'Entra, guri. Rápido. Eles estão vindo.',
    'end.9': '...Ah, mas que beleza.',
    'end.chapter': 'FIM DO CAPÍTULO 1',
    'end.tbc': 'Continua...',

    'cred.1': 'TEEWALD CITY',
    'cred.2': 'Capítulo 1 — A Cidade Adormecida',
    'cred.3': 'Pixel art, música e efeitos',
    'cred.4': 'gerados inteiramente em código',
    'cred.5': 'Inspirado na serra do sul do Brasil,',
    'cred.6': 'nas araucárias, nas casas de enxaimel',
    'cred.7': 'e nas histórias contadas à beira do fogão.',
    'cred.8': 'Obrigado por jogar!'
  };

  L.en = {
    'boot.press': 'PRESS START',
    'boot.hint': 'ENTER / Z / TAP',
    'boot.lang': 'CHOOSE LANGUAGE',

    'menu.new': 'NEW GAME',
    'menu.continue': 'CONTINUE',
    'menu.options': 'OPTIONS',
    'menu.controls': 'CONTROLS',
    'title.sub': 'CHAPTER 1 — THE SLEEPING TOWN',
    'title.copy': '© 2026  TEEWALD CITY',

    'opt.title': 'OPTIONS',
    'opt.lang': 'LANGUAGE',
    'opt.crt': 'CRT FILTER',
    'opt.chroma': 'CHROMATIC ABERRATION',
    'opt.aspect': 'ASPECT',
    'opt.music': 'MUSIC',
    'opt.sfx': 'SOUND FX',
    'opt.full': 'FULLSCREEN',
    'opt.back': 'BACK',
    'on': 'ON',
    'off': 'OFF',
    'aspect.square': 'SQUARE PIXELS',
    'aspect.tv': 'TV 4:3',
    'lang.name': 'ENGLISH',

    'ctrl.title': 'CONTROLS',
    'ctrl.move': 'MOVE',
    'ctrl.jump': 'JUMP',
    'ctrl.attack': 'ATTACK / COMBO',
    'ctrl.special': 'SPIN SPECIAL',
    'ctrl.pause': 'PAUSE',
    'ctrl.read': 'READ SIGNS',
    'ctrl.keys1': 'ARROWS / WASD',
    'ctrl.keys2': 'Z / SPACE / K',
    'ctrl.keys3': 'X / J',
    'ctrl.keys4': 'C / L',
    'ctrl.keys5': 'ENTER / ESC',
    'ctrl.keys6': '↑ NEAR A SIGN',
    'ctrl.pad': 'USB gamepads and touch screens work too.',

    'pause': 'PAUSED',
    'pause.resume': 'RESUME',
    'pause.quit': 'QUIT TO TITLE',

    'hud.score': 'SCORE',
    'go': 'GO',
    'fight': 'FIGHT!',
    'stage1.num': 'STAGE 1',
    'stage1.name': 'THE SLEEPING TOWN',
    'continue': 'CONTINUE?',
    'gameover': 'GAME OVER',
    'clear': 'STAGE CLEAR',
    'tally.score': 'SCORE',
    'tally.time': 'TIME BONUS',
    'tally.hp': 'HEALTH BONUS',
    'tally.total': 'TOTAL',
    'checkpoint': 'CANDLE LIT',

    'hint.move': '◀ ▶ WALK    Z JUMP    X ATTACK',
    'hint.combo': 'X X X  =  COMBO!   JUMP + X  =  FLYING KICK',
    'hint.special': 'C  =  SPIN SPECIAL (costs a little health)',
    'hint.break': 'Smash crates and barrels: there is food inside!',
    'hint.read': '↑  READ',

    'item.cuca': 'CUCA CAKE',
    'item.linguica': 'SAUSAGE',
    'item.chimarrao': 'CHIMARRÃO',
    'item.pinhao': 'PINE NUT',
    'item.medalha': 'ST. CHRISTOPHER MEDAL',
    'item.1up': '1 UP!',

    'en.ghost': 'HAUNT',
    'en.flame': 'FLAMEHEAD',
    'en.shadow': 'SHADE',
    'en.crow': 'CROW',
    'en.crate': 'CRATE',
    'en.barrel': 'BARREL',
    'boss.name': 'THE GIANT CYCLOPS',

    'name.arno': 'ARNO',
    'name.radio': 'RADIO',
    'name.voice': '???',
    'name.frida': 'DONA FRIDA',

    'intro.skip': 'START: SKIP',
    'intro.place': 'Southern Brazil',
    'intro.date': 'Autumn, 1997',
    'intro.road': 'Highland Road — 11:47 PM',
    'intro.d1': 'Teewald City... Twenty years since I last drove up this range.',
    'intro.d2': 'My father ran this route every week. I rode along, just a kid, in the passenger seat.',
    'intro.d3': 'Look at those araucarias... Some of them were already old before the first settlers came.',
    'intro.d4': 'On full-moon nights the town glowed down below. The half-timbered houses, the church tower...',
    'intro.d5': 'The smell of roast potatoes, the Potato Festival, the little band playing in the square... The most beautiful town in the world.',
    'intro.r1': '...ksshh... attention, drivers... kssh... thick fog on the range...',
    'intro.r2': '...kshh... do not... do NOT enter Teewald... kssshhh...',
    'intro.d6': 'Huh? ...Old radio. Nothing but static up here.',
    'intro.d7': 'Good Lord, where did this fog come from... I can\'t see a thing.',
    'intro.d8': 'Easy, Arno. Slow down. Almost there...',

    'wake.1': '...Huh...?',
    'wake.2': 'Ugh... my head...',
    'wake.3': 'Where\'s the truck? I was coming down the range... and now...',
    'wake.4': 'These half-timbered houses... the church tower... It\'s Teewald City. Just like I remember it.',
    'wake.5': 'But where is everyone? Not a single window lit... not even a dog barking...',
    'wake.6': '...What the hell is that?!',

    'mid.bridge': 'The creek... My father taught me to fish down there.',
    'mid.cemetery': 'The old settlers\' cemetery... Lit candles? Who lit all these candles?',
    'mid.square': 'The church square. The bell... Is someone in there?',

    'sign.welcome': 'WELCOME TO TEEWALD CITY\nFounded in 1852 by settlers from the Rhine.\n"Willkommen!"',
    'sign.festa': 'POTATO FESTIVAL — 25TH EDITION\nDance, brass band and the Potato Queen.\nJune, 1977.',
    'sign.missing': 'MISSING SINCE THE FOG:\nthe Schmitt, Kessler, Weber families...\n(the rest of the paper is torn)',
    'sign.bridge': 'CREEK BRIDGE\nCareful: loose planks.',
    'sign.cemetery': 'SETTLERS\' CEMETERY\n"Here rest those who came from afar."',
    'sign.bakery': 'WEBER BAKERY\nGrape, banana and crumb cuca cakes.\nClosed.',

    'boss.1': 'What in God\'s name is that...?!',
    'boss.2': 'Alright, ugly. Bring it!',

    'end.1': 'Is it... over?',
    'end.2': 'Arno... Arno Becker.',
    'end.3': 'Who\'s there? How do you know my name?',
    'end.4': 'I blessed you when you were a boy. You were afraid of the dark, remember?',
    'end.5': '...Dona Frida? The old healer? But you...',
    'end.6': 'For twenty years the night has never ended in Teewald. They came with the fog.',
    'end.7': 'And the town waited. Waited for someone brave enough to come back.',
    'end.8': 'Come inside, boy. Quickly. They\'re coming.',
    'end.9': '...Oh, just wonderful.',
    'end.chapter': 'END OF CHAPTER 1',
    'end.tbc': 'To be continued...',

    'cred.1': 'TEEWALD CITY',
    'cred.2': 'Chapter 1 — The Sleeping Town',
    'cred.3': 'Pixel art, music and sound',
    'cred.4': 'generated entirely in code',
    'cred.5': 'Inspired by the highlands of southern Brazil,',
    'cred.6': 'the araucarias, the half-timbered houses',
    'cred.7': 'and the stories told by the wood stove.',
    'cred.8': 'Thanks for playing!'
  };

  TC.LANG = L;
  TC.t = function (key) {
    var lang = TC.opts.lang || 'pt';
    var s = L[lang][key];
    if (s == null) s = L.pt[key];
    return s == null ? key : s;
  };
})();
