'use strict';
/* Teewald City — textos do capítulo 6 ("A Noite do Pelznickel") */
(function () {
  var L = TC.LANG;

  Object.assign(L.pt, {
    'chap.6': '6 — A NOITE DO PELZNICKEL',
    'chap.6.d': 'Um vulto de barba-de-velho leva as crianças da Linha Esperança num saco.',
    'stage6.num': 'FASE 6',
    'stage6.name': 'A NOITE DO PELZNICKEL',
    'mission6': 'Encontre as três crianças levadas pelo Pelznickel. No caminho, a casa de pedra da Oma Hedwig guarda o diário.',
    'end6.chapter': 'FIM DO CAPÍTULO 6',
    'end6.next': 'Capítulo 7: A Última Fita',
    'cred6.2': 'Capítulo 6 — A Noite do Pelznickel',
    'cred6.3': 'Lendas, costumes e lugares',
    'cred6.4': 'o Pelznickel e a barba-de-velho,',
    'cred6.5': 'o bolão de nove pinos e a venda,',
    'cred6.6': 'a escola da linha e o Erlkönig.',

    'en.c6scare': 'ESPANTALHO',
    'en.c6barba': 'BARBA-DE-VELHO',
    'en.c6bowler': 'JOGADOR DE BOLÃO',
    'boss6.name': 'O PELZNICKEL',
    'boss6b.name': 'JOHANN VOGT, O MESTRE-ESCOLA',
    'item.c6ball': 'BOLA DE BOLÃO',

    'hint.c6ball': 'BOLA DE BOLÃO:  V  ou  ↑ + X  =  ARREMESSAR',
    'hint.c6ball@touch': 'BOLA DE BOLÃO:  ↑ + B  =  ARREMESSAR',
    'hint.c6ball@pad': 'BOLA DE BOLÃO:  {shoot}  ou  ↑ + {attack}  =  ARREMESSAR',
    'hint.c6grab': 'AGARRADO! ATAQUE E PULE PARA SE SACUDIR!',
    'hint.c6sack': 'NO SACO! APERTE  X  SEM PARAR PARA SAIR!',
    'hint.c6sack@touch': 'NO SACO! APERTE  B  SEM PARAR PARA SAIR!',
    'hint.c6sack@pad': 'NO SACO! APERTE  {attack}  SEM PARAR PARA SAIR!',
    'hint.boss6': 'PULE A CORRENTE E A BOLA DE MUSGO! SAIA DO X DE GIZ!',
    'hint.c6furnace': 'FAÇA A BOLA DE MUSGO BATER NA FORNALHA!',
    'hint.boss6b': 'FUJA DO GIZ E DA SOMBRA DOS NOMES!',

    'c6.alle': 'ALLE NEUNE!',
    'c6.gutholz': 'Gut Holz!',
    'c6.grab': 'AGARROU!',
    'c6.shake': 'SOLTOU!',
    'c6.torn': 'RASGOU O SACO!',
    'c6.fire': 'O MUSGO PEGOU FOGO!',
    'c6.gebetet': 'Hast du gebetet?',
    'c6.list': 'A CHAMADA!',
    'c6.mae': 'MÃE!',
    'c6.socorro': 'SOCORRO!',
    'c6.vo': 'VÔ!',
    'c6.dodge': 'Ruhe!',

    /* ---------- prólogo: a igreja e a cabine ---------- */
    'ch6.card1': 'Teewald City — a noite seguinte',
    'ch6.card2': 'Igreja Matriz de São Miguel Arcanjo',
    'ch6.card3': 'A estrada da Linha Esperança',
    'c6p.0': 'Mais um mate, Ewald? A água ainda tá boa.',
    'c6p.0b': 'Bah, Frida. Depois de uma cobra de fogo, até mate frio desce bem.',
    'c6p.1': 'Dona Frida! Levaram as crianças da Linha Esperança! Três!',
    'c6p.2': 'Um bicho todo de barba-de-velho, de corrente e saco nas costas! A minha neta, a Lena, tava junto!',
    'c6p.3': 'Pelznickel...',
    'c6p.4': 'O Pelznickel do Natal? Que dava vara em quem não rezava?',
    'c6p.5': 'O de verdade não vem no Natal. Vem cobrar.',
    'c6p.6': 'Na Linha Esperança fica a casa de pedra da tua bisavó, Frida.',
    'c6p.7': 'O diário da Oma Hedwig tá lá. Ninguém mexe naquela casa desde 1901.',
    'c6p.8': 'Se alguém sabe o que esse bicho quer, é ela.',
    'c6p.9': 'Dessa vez eu dirijo.',
    'c6c.1': 'Wer reitet so spät durch Nacht und Wind? Es ist der Vater mit seinem Kind...',
    'c6c.2': '...Mein Sohn, es ist ein Nebelstreif.',
    'c6c.3': '"Meu filho, é só cerração." Tu pedia esse poema toda noite, guri.',
    'c6c.4': 'O fim dele é triste, pai.',
    'c6c.5': 'Por isso eu nunca lia o fim.',
    'c6c.6': 'Hoffnungsschneiss. A picada da esperança.',
    'c6c.7': 'A primeira picada de 1852. Daqui pra dentro a cerração é mais grossa.',

    /* ---------- na fase ---------- */
    'ew6.1': 'Eu fico com o motor ligado e os faróis acesos. Vai, guri. Traz as crianças.',
    'b6.start': 'Linha Esperança. Estrada de chão, cerca de arame... e nem um cachorro latindo.',
    'b6.estufa': 'As estufas de fumo. A fornalha ainda tá acesa: alguém botou lenha faz pouco.',
    'b6.tree': 'Barba-de-velho pendurada nos galhos. A vó dizia que era a barba do Pelznickel.',
    'b6.corn': 'O milharal. Na cerração, cada espantalho parece gente parada me olhando.',
    'b6.venda': 'A venda do Seu Arnoldo. Querosene, fumo em corda, cachaça... e fiado só amanhã.',
    'b6.bolao': 'A cancha de bolão. Domingo de tarde a linha inteira vinha aqui. Gut Holz!',
    'b6.cem': 'O cemitério da família. Cruz de ferro forjado, coisa dos antigos.',
    'b6.school': 'A escola da linha. O pai estudou aqui. O vô também.',
    'b6.inside': 'Tem gente rezando lá dentro... Vozes de criança.',
    'b6.yard': 'O pátio da escola. A estufa do lado ainda tá com a fornalha acesa.',
    'sign6.porteira': 'LINHA ESPERANÇA — 1852\nHoffnungsschneiss: a picada da esperança,\na primeira aberta pelos colonos do Hoffnung.',
    'sign6.estufa': 'ESTUFA DE FUMO\nFumo em folha, curado a lenha.\nNão deixar a fornalha apagar de noite!',
    'sign6.venda': 'VENDA ESPERANÇA — SECOS E MOLHADOS\nQuerosene, fumo em corda, erva e cachaça.\nFIADO SÓ AMANHÃ.',
    'sign6.bolao': 'SOCIEDADE DE BOLÃO ESPERANÇA — 1903\nNove pinos. Quem derrubar todos grita\n"ALLE NEUNE!" — Gut Holz!',
    'sign6.cross': 'Cruz de ferro dos Schmitt:\n"Lotte Schmitt, 1891 - 1898".\nSumiu na cerração aos sete anos.',
    'sign6.grave': 'HIER RUHT IN GOTT\nHedwig, 1834 - 1901.\nRiscado a prego: "Sie hat nicht unterschrieben."\n(Ela não assinou.)',
    'sign6.school': 'ESCOLA DA LINHA ESPERANÇA — 1871\nPor baixo da tinta ainda se lê: DEUTSCHE SCHULE.\nFechada em 1938; reaberta em português.',
    'sign6.alfabeto': 'Cartaz do alfabeto: A de Anjo, B de Bolão, C de Cuca...\nNo canto, a lápis: "Lena, 3ª série".',

    /* o diário */
    'd6.1': 'A casa de pedra da Oma Hedwig. 1853, tá entalhado na verga da porta.',
    'd6.2': 'Não tava trancada... Em cima da mesa, debaixo de cem anos de pó: o diário.',
    'd6.h0': 'Tagebuch. Escrevo para quem vier depois de mim, porque os homens juraram nunca contar.',
    'd6.h1': 'No ano de 1852 o veleiro Hoffnung ficou quarenta dias parado na calmaria. Nem uma brisa.',
    'd6.h1b': 'A água acabou no trigésimo segundo dia. O mar era um espelho, e o sol não perdoava.',
    'd6.h2': 'No porão as crianças ardiam em febre. A pequena dos Schmitt foi a primeira que a gente perdeu.',
    'd6.h3': 'O mestre-escola Johann Vogt, que puxava as rezas a bordo, desceu sozinho com o lampião. Lá no fundo tinha dois olhos.',
    'd6.h4': 'Uma mão comprida e branca saiu do escuro e ofereceu a pena. Vento para o navio...',
    'd6.h4b': '...e em troca, um de cada família, a cada geração, até a dívida estar paga.',
    'd6.h5': 'Os homens assinaram o Livro de Bordo com um X. Schmitt, Weber, Kessler, Becker. Todos.',
    'd6.h6': 'Eu não assinei. Cuspi no livro. O Vogt me olhou como quem olha uma criança que não rezou.',
    'd6.h7': 'Na mesma noite o vento voltou. O sino do Hoffnung hoje bate na torre da Matriz.',
    'd6.h7b': 'Se um dia alguém desfizer os pagamentos, a dívida inteira vence de uma vez. Que Deus tenha piedade de Teewald.',
    'd6.cap0': 'O DIÁRIO DA OMA HEDWIG',
    'd6.cap1': 'A CALMARIA — 1852',
    'd6.cap2': 'O PORÃO',
    'd6.cap3': 'O MESTRE-ESCOLA',
    'd6.cap4': 'A PENA',
    'd6.cap5': 'O LIVRO DE BORDO',
    'd6.cap6': 'A QUE NÃO ASSINOU',
    'd6.cap7': 'O VENTO',
    'd6.a': 'Um de cada família, a cada geração... Os nomes na escada do baile não eram sumiços. Eram pagamentos.',
    'd6.b': 'E eu tirei todo mundo de lá. Devolvi tudo de uma vez.',
    'd6.c': 'Bah... A dívida inteira venceu. E o cobrador tá na escola.',

    /* a escola */
    'k6.1': 'Vater unser, der du bist im Himmel... geheiligt werde dein Name...',
    's6.1': 'Schmitt, 1898... Weber, 1931... Becker, 1977... Kessler, 1997...',
    's6.2': '...Becker, 1997. Sou eu.',
    'p6.1': 'Hast du gebetet, Arno Becker? Tu também tá na lista.',
    's6.3': 'Larga essas crianças, bicho!',
    'p6.2': 'Wer nicht betet, kommt in den Sack. Quem não reza vai pro saco.',
    's6.4': 'Pela janela dos fundos! Volta aqui!',

    /* o chefe */
    'bs6.1': 'Solta as crianças, Pelznickel!',
    'bs6.2': 'Um de cada família, a cada geração. Hoje eu levo três... e um Becker.',
    'bs6.3': 'Musgo seco... e a fornalha da estufa acesa ali do lado. Se esse bicho rolar pra lá...',
    'v6.1': 'Debaixo do musgo... um homem de colarinho. Johann Vogt, o mestre-escola do Hoffnung.',
    'v6.2': 'Setzt euch! Sentem-se. A chamada ainda não terminou.',
    'c6e.1': 'As crianças tavam morrendo no navio. Quarenta dias de calmaria. Eu só queria vento.',
    'c6e.2': 'E agora tu leva as crianças dos outros.',

    /* o final */
    'e6.1': 'O trato era um por família, por geração. Alguém tinha que cobrar.',
    'e6.2': 'Acabou a cobrança.',
    'e6.3': 'Não acaba. Quando o cobrador falha, o credor vem buscar pessoalmente.',
    'e6.4': 'E tu devolveu tudo o que estava no baile, Becker. A dívida inteira venceu.',
    'e6.5': 'Vô! Vô Arnoldo!',
    'e6.6': 'Lena! Graças a Deus... Vem cá, minha guria. Vem cá.',
    'e6.7': 'Sete badaladas... Ele vem hoje à noite.',
    'e6.8': 'O sino da Matriz... Ninguém subiu na torre.',
    'e6.9': 'Vamos, pai. Hoje a cidade inteira dorme na igreja.',
    'e6.cap': 'A cerração de todas as linhas escorre serra abaixo, para Teewald.'
  });

  Object.assign(L.en, {
    'chap.6': '6 — THE NIGHT OF THE PELZNICKEL',
    'chap.6.d': 'A figure in old man\'s beard carries off the children of Linha Esperança in a sack.',
    'stage6.num': 'STAGE 6',
    'stage6.name': 'THE NIGHT OF THE PELZNICKEL',
    'mission6': 'Find the three children taken by the Pelznickel. On the way, Oma Hedwig\'s stone house keeps her diary.',
    'end6.chapter': 'END OF CHAPTER 6',
    'end6.next': 'Chapter 7: The Last Ribbon',
    'cred6.2': 'Chapter 6 — The Night of the Pelznickel',
    'cred6.3': 'Legends, customs and places',
    'cred6.4': 'the Pelznickel and the old man\'s beard,',
    'cred6.5': 'nine-pin bowling and the country store,',
    'cred6.6': 'the colony school and the Erlkönig.',

    'en.c6scare': 'SCARECROW',
    'en.c6barba': 'OLD MAN\'S BEARD',
    'en.c6bowler': 'NINEPIN PLAYER',
    'boss6.name': 'THE PELZNICKEL',
    'boss6b.name': 'JOHANN VOGT, THE SCHOOLMASTER',
    'item.c6ball': 'NINEPIN BALL',

    'hint.c6ball': 'NINEPIN BALL:  V  or  ↑ + X  =  ROLL IT',
    'hint.c6ball@touch': 'NINEPIN BALL:  ↑ + B  =  ROLL IT',
    'hint.c6ball@pad': 'NINEPIN BALL:  {shoot}  or  ↑ + {attack}  =  ROLL IT',
    'hint.c6grab': 'GRABBED! ATTACK AND JUMP TO SHAKE IT OFF!',
    'hint.c6sack': 'IN THE SACK! MASH  X  TO GET OUT!',
    'hint.c6sack@touch': 'IN THE SACK! MASH  B  TO GET OUT!',
    'hint.c6sack@pad': 'IN THE SACK! MASH  {attack}  TO GET OUT!',
    'hint.boss6': 'JUMP THE CHAIN AND THE MOSS BALL! LEAVE THE CHALK X!',
    'hint.c6furnace': 'MAKE THE MOSS BALL HIT THE FURNACE!',
    'hint.boss6b': 'DODGE THE CHALK AND THE NAMES\' SHADOWS!',

    'c6.alle': 'ALLE NEUNE!',
    'c6.gutholz': 'Gut Holz!',
    'c6.grab': 'GRABBED!',
    'c6.shake': 'SHOOK IT OFF!',
    'c6.torn': 'TORE THE SACK!',
    'c6.fire': 'THE MOSS CAUGHT FIRE!',
    'c6.gebetet': 'Hast du gebetet?',
    'c6.list': 'ROLL CALL!',
    'c6.mae': 'MOM!',
    'c6.socorro': 'HELP!',
    'c6.vo': 'GRANDPA!',
    'c6.dodge': 'Ruhe!',

    'ch6.card1': 'Teewald City — the next night',
    'ch6.card2': 'Mother Church of Saint Michael the Archangel',
    'ch6.card3': 'The road to Linha Esperança',
    'c6p.0': 'Another mate, Ewald? The water\'s still good.',
    'c6p.0b': 'Bah, Frida. After a fire snake, even cold mate goes down fine.',
    'c6p.1': 'Dona Frida! They took the children of Linha Esperança! Three of them!',
    'c6p.2': 'A creature all covered in old man\'s beard, with a chain and a sack on its back! My granddaughter Lena was with them!',
    'c6p.3': 'Pelznickel...',
    'c6p.4': 'The Christmas Pelznickel? The one who switched kids who didn\'t pray?',
    'c6p.5': 'The real one doesn\'t come at Christmas. He comes to collect.',
    'c6p.6': 'Your great-grandmother\'s stone house is in Linha Esperança, Frida.',
    'c6p.7': 'Oma Hedwig\'s diary is there. Nobody has touched that house since 1901.',
    'c6p.8': 'If anyone knows what that creature wants, it\'s her.',
    'c6p.9': 'This time I\'m driving.',
    'c6c.1': 'Wer reitet so spät durch Nacht und Wind? Es ist der Vater mit seinem Kind...',
    'c6c.2': '...Mein Sohn, es ist ein Nebelstreif.',
    'c6c.3': '"My son, it\'s only a wisp of fog." You asked for that poem every night, kid.',
    'c6c.4': 'It has a sad ending, Dad.',
    'c6c.5': 'That\'s why I never read the ending.',
    'c6c.6': 'Hoffnungsschneiss. The trail of hope.',
    'c6c.7': 'The first trail cut in 1852. From here on the fog gets thicker.',

    'ew6.1': 'I\'ll keep the engine running and the headlights on. Go, son. Bring those kids back.',
    'b6.start': 'Linha Esperança. Dirt road, barbed wire... and not one dog barking.',
    'b6.estufa': 'The tobacco barns. The furnace is still lit: someone fed it not long ago.',
    'b6.tree': 'Old man\'s beard hanging from the branches. Grandma said it was the Pelznickel\'s beard.',
    'b6.corn': 'The cornfield. In the fog, every scarecrow looks like someone standing there, watching me.',
    'b6.venda': 'Mr. Arnoldo\'s store. Kerosene, rope tobacco, cachaça... and credit only tomorrow.',
    'b6.bolao': 'The ninepin alley. Sunday afternoons the whole colony came here. Gut Holz!',
    'b6.cem': 'The family cemetery. Wrought-iron crosses, the old folks\' way.',
    'b6.school': 'The colony school. Dad studied here. Grandpa too.',
    'b6.inside': 'Someone\'s praying in there... Children\'s voices.',
    'b6.yard': 'The schoolyard. The barn next door still has its furnace burning.',
    'sign6.porteira': 'LINHA ESPERANÇA — 1852\nHoffnungsschneiss: the trail of hope,\nthe first one cut by the settlers of the Hoffnung.',
    'sign6.estufa': 'TOBACCO BARN\nLeaf tobacco, cured over firewood.\nDon\'t let the furnace go out at night!',
    'sign6.venda': 'ESPERANÇA STORE — DRY GOODS AND DRINKS\nKerosene, rope tobacco, yerba and cachaça.\nCREDIT ONLY TOMORROW.',
    'sign6.bolao': 'ESPERANÇA NINEPIN SOCIETY — 1903\nNine pins. Knock them all down and shout\n"ALLE NEUNE!" — Gut Holz!',
    'sign6.cross': 'The Schmitts\' iron cross:\n"Lotte Schmitt, 1891 - 1898".\nVanished in the fog at seven years old.',
    'sign6.grave': 'HIER RUHT IN GOTT\nHedwig, 1834 - 1901.\nScratched with a nail: "Sie hat nicht unterschrieben."\n(She did not sign.)',
    'sign6.school': 'LINHA ESPERANÇA SCHOOL — 1871\nUnder the paint you can still read: DEUTSCHE SCHULE.\nClosed in 1938; reopened in Portuguese.',
    'sign6.alfabeto': 'Alphabet poster: A for Angel, B for Bowling, C for Cake...\nIn the corner, in pencil: "Lena, 3rd grade".',

    'd6.1': 'Oma Hedwig\'s stone house. 1853, carved into the lintel.',
    'd6.2': 'It wasn\'t locked... On the table, under a hundred years of dust: the diary.',
    'd6.h0': 'Tagebuch. I write for whoever comes after me, because the men swore never to tell.',
    'd6.h1': 'In the year 1852 the sailing ship Hoffnung lay forty days becalmed. Not a breath of wind.',
    'd6.h1b': 'The water ran out on the thirty-second day. The sea was a mirror, and the sun showed no mercy.',
    'd6.h2': 'Down in the hold the children burned with fever. The little Schmitt girl was the first we lost.',
    'd6.h3': 'The schoolmaster Johann Vogt, who led the prayers on board, went down alone with the lantern. Deep in the dark were two eyes.',
    'd6.h4': 'A long white hand came out of the dark and offered the pen. Wind for the ship...',
    'd6.h4b': '...and in exchange, one from each family, every generation, until the debt is paid.',
    'd6.h5': 'The men signed the Ship\'s Log with an X. Schmitt, Weber, Kessler, Becker. All of them.',
    'd6.h6': 'I did not sign. I spat on the book. Vogt looked at me the way one looks at a child who didn\'t pray.',
    'd6.h7': 'That same night the wind came back. The Hoffnung\'s bell now rings in the Mother Church tower.',
    'd6.h7b': 'If one day someone undoes the payments, the whole debt falls due at once. God have mercy on Teewald.',
    'd6.cap0': 'OMA HEDWIG\'S DIARY',
    'd6.cap1': 'THE DOLDRUMS — 1852',
    'd6.cap2': 'THE HOLD',
    'd6.cap3': 'THE SCHOOLMASTER',
    'd6.cap4': 'THE PEN',
    'd6.cap5': 'THE SHIP\'S LOG',
    'd6.cap6': 'THE ONE WHO DID NOT SIGN',
    'd6.cap7': 'THE WIND',
    'd6.a': 'One from each family, every generation... The names on the ballroom stairs weren\'t disappearances. They were payments.',
    'd6.b': 'And I pulled everyone out of there. Gave it all back at once.',
    'd6.c': 'Bah... The whole debt fell due. And the collector is at the school.',

    'k6.1': 'Vater unser, der du bist im Himmel... geheiligt werde dein Name...',
    's6.1': 'Schmitt, 1898... Weber, 1931... Becker, 1977... Kessler, 1997...',
    's6.2': '...Becker, 1997. That\'s me.',
    'p6.1': 'Hast du gebetet, Arno Becker? You\'re on the list too.',
    's6.3': 'Let go of those kids, you beast!',
    'p6.2': 'Wer nicht betet, kommt in den Sack. Whoever doesn\'t pray goes in the sack.',
    's6.4': 'Out the back window! Come back here!',

    'bs6.1': 'Let the children go, Pelznickel!',
    'bs6.2': 'One from each family, every generation. Tonight I take three... and a Becker.',
    'bs6.3': 'Dry moss... and the barn furnace burning right over there. If that thing rolls that way...',
    'v6.1': 'Under the moss... a man in a high collar. Johann Vogt, the Hoffnung\'s schoolmaster.',
    'v6.2': 'Setzt euch! Sit down. Roll call isn\'t over.',
    'c6e.1': 'The children were dying on that ship. Forty days becalmed. All I wanted was wind.',
    'c6e.2': 'And now you take other people\'s children.',

    'e6.1': 'The pact was one per family, per generation. Someone had to collect.',
    'e6.2': 'The collecting is over.',
    'e6.3': 'It never ends. When the collector fails, the creditor comes in person.',
    'e6.4': 'And you gave back everything that was at the dance, Becker. The whole debt is due.',
    'e6.5': 'Grandpa! Grandpa Arnoldo!',
    'e6.6': 'Lena! Thank God... Come here, my girl. Come here.',
    'e6.7': 'Seven tolls... He comes tonight.',
    'e6.8': 'The church bell... Nobody went up the tower.',
    'e6.9': 'Come on, Dad. Tonight the whole town sleeps in the church.',
    'e6.cap': 'The fog from every colony road pours down the hills, toward Teewald.'
  });
})();
