'use strict';
/* Teewald City — textos do capítulo 7 ("A Última Fita"): a noite das sete badaladas, a batalha final na Matriz
   de São Miguel Arcanjo contra der Alte, o Antigo, e o fim do jogo. */
(function () {
  var L = TC.LANG;

  Object.assign(L.pt, {
    'chap.7': '7 — A ÚLTIMA FITA',
    'chap.7.d': 'O sino da Matriz bate sete vezes. O Antigo vem cobrar a dívida de 1852.',
    'stage7.num': 'FASE 7',
    'stage7.name': 'A ÚLTIMA FITA',
    'mission7': 'Segure o cerco, desça à cripta, suba a torre do sino... e amarre o Antigo com as sete fitas.',
    'end7.chapter': 'FIM DO CAPÍTULO 7',
    'name.erwin': 'SEU ERWIN',
    'name.ewaldOld': 'EWALD BECKER',
    'name.kessler7': 'SEU KESSLER',
    'name.ingrid7': 'INGRID WEBER',

    /* ---------- prólogo ---------- */
    'ch7.card1': 'Matriz de São Miguel Arcanjo',
    'ch7.card2': 'A noite das sete badaladas',
    'c7.p1': 'O último verso da reza da Oma Hedwig nunca foi bordado. Não se borda.',
    'c7.p2': 'Se diz em voz alta, com a cidade inteira junta. Por isso o pau-de-fita era de todo mundo.',
    'c7.p3': 'E a gente esqueceu.',
    'c7.p4': 'Hoje a gente lembra. Sete fitas, guri. Uma de cada canto de Teewald.',
    'c7.f1': 'A fita do teu batizado, Arno. Eu guardei.',
    'c7.f2': 'A última fita bordada da Oma Hedwig. Essa eu trouxe do toco.',
    'c7.f3': 'A minha faixa de Rainha da Batata.',
    'c7.f4': 'A linha vermelha do sapato da Hilde. Ficou no chão do pesponto.',
    'c7.f5': 'Uma tira de taquara do meu balaio. Pra amarração ser de todo mundo dessa vez.',
    'c7.f6': 'A fita do Kerb da Linha Esperança.',
    'c7.f7': 'E essa... a fitinha que o pai pendurou no retrovisor em 1977. Eu carrego ela há vinte anos.',
    'c7.f7b': '...Tu guardou.',
    'c7.r1': 'BATIZADO', 'c7.r2': 'OMA HEDWIG', 'c7.r3': 'RAINHA', 'c7.r4': 'HILDE', 'c7.r5': 'TAQUARA', 'c7.r6': 'KERB', 'c7.r7': 'RETROVISOR',
    'c7.p5': 'Achei isso no salão do baile, Arno. O laço do Moço. Ficou largado no meio da pista.',
    'c7.p6': 'Bah... laço de diabo?',
    'c7.p7': 'Era. Agora é bento. Bala acaba, laço não.',
    'c7.p8': 'E eu fico lá em cima, na janela, com a espingarda. Rei do Tiro de 97, guri!',
    'c7.p9': 'Escutem... O sino tá batendo sozinho.',
    'c7.p10': 'Ele chegou. Vai, guri. A gente segura a reza aqui dentro.',
    'c7.p11': 'Arno! ...Volta pra casa, ouviu?',
    'c7.p12': 'Deixa a água no fogo, pai. Essa noite acaba hoje.',
    'c7.lasso': 'LAÇO BENTO',
    'c7.toll': 'BLÉM...',

    /* ---------- na fase ---------- */
    'hint.lasso': 'V  ou  ↑ + X  =  LAÇO BENTO',
    'hint.lasso@touch': '↑ + B  =  LAÇO BENTO',
    'hint.lasso@pad': '{shoot}  ou  ↑ + {attack}  =  LAÇO BENTO',
    'c7.hud.lasso': 'LAÇO',
    'c7.h1': 'Vai, guri! Deixa que eu cubro daqui de cima!',
    'c7.bang': 'PÁ!',
    'c7.b.square': 'A praça tá tomada... Tem bicho de todos os cantos de Teewald aqui.',
    'c7.b.cem': 'O cemitério da colônia. Aqui tão enterrados os Becker também.',
    'c7.b.door': 'A porta lateral. Desce pra cripta, embaixo da igreja.',
    'c7.b.lamp': 'Um lampião pendurado na porta da cripta. Esse vem comigo.',
    'c7.b.book': 'O Livro de Bordo do Hoffnung... Todas as famílias assinaram com um X. Todas menos uma.',
    'c7.b.tower': 'A escada da torre. O sino tá lá em cima... e não para de bater.',
    'c7.b.clock': 'A máquina do relógio. Os ponteiros tão parados em onze e quarenta e sete.',
    'c7.b.dark': 'Escuro que nem breu... Não enxergo nem a minha mão.',
    'c7.b.flies': 'Vaga-lumes... A luz da Boitatá! Ela não esqueceu da gente.',
    'c7.b.bell': 'O sino do Hoffnung. Veio no navio, em 1852... E lá embaixo... ele entrou na igreja!',
    'c7.s.matriz': 'IGREJA MATRIZ DE SÃO MIGUEL ARCANJO — 1855. As portas estão trancadas por dentro. Lá dentro, a cidade reza.',
    'c7.s.becker': 'FAMÍLIA BECKER. "Hier ruht in Gott" — aqui descansa em Deus. Tem flor fresca no túmulo do vô.',
    'c7.s.door': 'CRIPTA. Silêncio: aqui descansam os padres de Teewald.',
    'c7.s.padre': 'PE. ANTÔNIO SCHNEIDER, 1859–1931. Nunca deixou tocar o sino à meia-noite. Ninguém sabia por quê.',
    'c7.s.stone': 'PEDRA FUNDAMENTAL DA MATRIZ — 1855. Debaixo dela, num cofre de ferro aberto, o Livro de Bordo.',
    'c7.s.book': 'LIVRO DE BORDO DO VELEIRO HOFFNUNG — 1852. Uma página de nomes, cada um com um X do lado. Embaixo, à parte: "Hedwig" — riscado com tanta raiva que a pena rasgou o papel.',
    'c7.s.tower': 'TORRE DO SINO. Proibido subir sem o sacristão.',
    'c7.s.clock': 'RELÓGIO DA MATRIZ. Oferta da Sociedade de Tiro, 1923.',
    'c7.s.bell': '"HOFFNUNG — 1852". O sino do navio, fundido de novo em Teewald.',
    'c7.e1a': 'O Ciclope?! Eu te derrubei na praça!',
    'c7.e1b': 'Não... É só um eco. A cerração lembra de tudo.',
    'c7.e1c': 'Volta pra cerração, que é o teu lugar.',
    'c7.e2a': 'Boa noite, Becker. Sentiu saudade da valsa?',
    'c7.e2b': 'Tu é só um eco, Moço.',
    'c7.e2c': 'Eco também dança.',
    'c7.e2d': '...a última música... é tua...',
    'c7.echo1': 'ECO: O CICLOPE GIGANTE',
    'c7.echo2': 'ECO: O MOÇO DO BAILE',
    'c7.hi1': 'Um vão... Não dá pra pular isso.',
    'c7.hi2': 'Tu abriu a minha porta. Eu costuro o teu caminho.',
    'c7.hi3': 'Obrigado, Hilde.',
    'c7.hi4': 'Agora eu tenho a noite inteira pra dançar.',
    'en.c7hand': 'MÃO-COMPRIDA',
    'en.c7cyclops': 'ECO DO CICLOPE',
    'en.c7moco': 'ECO DO MOÇO',

    /* ---------- o chefe ---------- */
    'boss7.name': 'DER ALTE — O ANTIGO',
    'c7.a1': 'Becker. Cento e quarenta e cinco anos eu esperei por esta noite.',
    'c7.a2': 'Vocês assinaram. O vento veio. Um de cada família, a cada geração.',
    'c7.a3': 'Ninguém daqui assinou nada contigo.',
    'c7.a4': 'O sangue assinou. E tu devolveu tudo o que estava no baile. A dívida inteira venceu.',
    'c7.a5': 'Então vem cobrar.',
    'hint.c7p1': 'BATA NAS MÃOS!  SAIA DA SOMBRA!',
    'hint.c7fog': 'NA CERRAÇÃO, OLHE OS OLHOS... E PULE!',
    'hint.c7grab': 'ELE PEGOU ALGUÉM!  BATA NA MÃO!',
    'hint.c7p2': 'FIQUE PERTO DO LAMPIÃO DA HEDWIG!',
    'hint.c7p3': 'DEFENDA OS DANÇARINOS!  BATA NAS MÃOS!',
    'hint.c7rope': 'PUXE A CORDA DO SINO!   X  PERTO DA CORDA',
    'hint.c7rope@touch': 'PUXE A CORDA DO SINO!   B  PERTO DA CORDA',
    'hint.c7rope@pad': 'PUXE A CORDA DO SINO!   {attack}  PERTO DA CORDA',
    'c7.s1': 'Lembra, Hedwig? Quarenta dias de calmaria. As crianças chorando no porão.',
    'c7.s2': 'O navio... É o porão do Hoffnung!',
    'c7.s3': 'Agora tu entende por que eu não assinei.',
    'c7.s4': 'Fica perto da minha luz, guri. Lampião de benzedeira ele não aguenta.',
    'c7.s5': 'Oma Hedwig...',
    'c7.d1': 'O resto não é comigo, guri. É com a cidade.',
    'c7.d2': 'Agora, gente! Pro pau-de-fita! Erwin, a valsa!',
    'c7.d3': 'Um, dois, três... e um, dois, três!',
    'c7.tie': '{n}ª FITA!',
    'c7.grabbed': 'A DANÇA PAROU!',
    'c7.freed': 'SOLTOU!',
    'c7.heal': 'O MEDO ALIMENTA O ANTIGO!',
    'c7.dazzle': 'A LUZ DA HEDWIG!',
    'c7.k1': 'Falta um Becker. Me dá o velho e eu solto a cidade.',
    'c7.k2': 'Ele tem razão, guri. Eu fiquei vinte anos devendo.',
    'c7.k3': 'Ninguém mais paga nada. Nem tu, pai.',
    'c7.k4': 'A dívida é de todos. E ninguém paga.',
    'c7.k5': 'Todo mundo junto, agora. Como a Oma Hedwig ensinou.',
    'c7.v0': 'Was zusammen gepflanzt ist, wird zusammen gebunden.',
    'c7.v1': 'O que foi plantado junto, junto se amarra.',
    'c7.v2': 'O que se esqueceu, hoje se lembra.',
    'c7.v3': 'E a noite que veio no navio',
    'c7.v4': 'volta pro mar sem levar ninguém.',
    'c7.k6': 'Esse sino te chamou em 1852.',
    'c7.k7': 'Agora ele te manda embora.',
    'c7.pull': 'PUXA!',
    'c7.c0': '...o mar... de novo...',
    'c7.c1': 'Amanheceu...',
    'c7.c2': 'Olha o sol entrando pelos vitrais, guri.',

    /* ---------- o final ---------- */
    'c7.z1': 'O sol! Gente, o SOL!',
    'c7.z2': 'Vou abrir a venda hoje mesmo. Cerveja de graça pra todo mundo!',
    'c7.z3': 'Bah! Nunca dei tanto tiro na vida. Nem no Kerb de 82.',
    'c7.z4': 'Olha... O meu relógio tá andando.',
    'c7.z5': 'Pai! O teu cabelo...',
    'c7.z6': 'Bah... agora sim eu tô em casa.',
    'c7.z7': 'Vinte anos de uma vez só. Frida, tu ainda tem aquele chá pra dor nas costas?',
    'c7.z8': 'E cuia pra três. Senta, Ewald. Tu também, Arno.',
    'c7.ep1': 'Na baixada do arroio, o Seu Gerhard pregou uma placa de bronze no portão da fábrica.',
    'c7.ep2': 'No Morro dos Bugres, a placa velha foi arrancada. E o fogo de nó-de-pinho ficou aceso.',
    'c7.ep2r': 'Agora o fogo é de todos.',
    'c7.ep3': 'Na Linha Esperança, as crianças voltaram pra escola, a venda abriu, e no domingo alguém gritou na cancha de bolão:',
    'c7.ep3b': '"Gut Holz!"',
    'c7.ep4': 'Maio de 1998. 3ª Festa da Batata. As moças dançaram o pau-de-fita em volta de uma araucária nova, plantada no toco pelo Seu Kessler.',
    'c7.ep4b': 'Agora todo mundo sabe por quê.',
    'c7.yc': 'Rodovia da Serra — 6h12',
    'c7.y1': 'O pai fazia essa rota toda semana. E eu ia junto, guri ainda, no banco do carona.',
    'c7.y2': 'Agora o carona sou eu. E quem dirige é o guri. Bah, que mundo.',
    'c7.y3': '...104,5, a rádio da serra. Bom dia, Teewald. Céu limpo em toda a serra.',
    'c7.y4': 'Assobia aquela valsa, pai.',
    'c7.y5': 'A do baile?',
    'c7.y6': 'A da estrada.',
    'c7.fim': 'FIM',

    /* ---------- créditos dos sete capítulos ---------- */
    'cred7.2': 'Uma história em sete capítulos',
    'cred7.c1': 'Capítulo 1 — A Cidade Adormecida',
    'cred7.c2': 'Capítulo 2 — A Trilha das Fitas',
    'cred7.c3': 'Capítulo 3 — O Baile Debaixo da Terra',
    'cred7.c4': 'Capítulo 4 — O Último Turno',
    'cred7.c5': 'Capítulo 5 — A Noite Grande',
    'cred7.c6': 'Capítulo 6 — A Noite do Pelznickel',
    'cred7.c7': 'Capítulo 7 — A Última Fita',
    'cred7.leg': 'Lendas',
    'cred7.l1': 'der Alte, o Antigo, o Mão-Comprida',
    'cred7.l2': 'o pau-de-fita e as sete fitas bentas',
    'cred7.l3': 'o Moço do Baile e o pé de bode',
    'cred7.l4': 'a Moça do Serão',
    'cred7.l5': 'a Boiguaçu e a Boitatá',
    'cred7.l6': 'o Pelznickel e a barba-de-velho',
    'cred7.pla': 'Lugares',
    'cred7.p1': 'a serra e as araucárias,',
    'cred7.p2': 'a Mina Santa Bárbara, a fábrica Morgenstern,',
    'cred7.p3': 'a caverna do morro, a Linha Esperança',
    'cred7.p4': 'e a Matriz de São Miguel Arcanjo.',
    'cred7.peo': 'A gente de Teewald',
    'cred7.g1': 'Arno e Ewald Becker, Dona Frida, Dona Rosa,',
    'cred7.g2': 'Oma Hedwig, Hilde Weber, Ingrid Weber,',
    'cred7.g3': 'Seu Helmut, Seu Gerhard, Seu Arnoldo,',
    'cred7.g4': 'Seu Kessler, Seu Erwin e a bandinha, a Lena.',
    'cred7.code': 'Pixel art, música e efeitos',
    'cred7.code2': 'gerados inteiramente em código',
    'cred7.ded': 'Para quem ainda acende o fogo no inverno.',
    'cred7.thanks': 'Obrigado por jogar!'
  });

  Object.assign(L.en, {
    'chap.7': '7 — THE LAST RIBBON',
    'chap.7.d': 'The church bell tolls seven times. The Old One comes to collect the debt of 1852.',
    'stage7.num': 'STAGE 7',
    'stage7.name': 'THE LAST RIBBON',
    'mission7': 'Hold the siege, go down to the crypt, climb the bell tower... and bind the Old One with the seven ribbons.',
    'end7.chapter': 'END OF CHAPTER 7',
    'name.erwin': 'MR. ERWIN',
    'name.ewaldOld': 'EWALD BECKER',
    'name.kessler7': 'MR. KESSLER',
    'name.ingrid7': 'INGRID WEBER',

    'ch7.card1': 'Church of Saint Michael the Archangel',
    'ch7.card2': 'The night of the seven tolls',
    'c7.p1': 'The last verse of Oma Hedwig\'s prayer was never embroidered. It isn\'t sewn.',
    'c7.p2': 'It\'s said out loud, with the whole town together. That\'s why the ribbon pole belonged to everyone.',
    'c7.p3': 'And we forgot.',
    'c7.p4': 'Tonight we remember. Seven ribbons, boy. One from every corner of Teewald.',
    'c7.f1': 'The ribbon from your baptism, Arno. I kept it.',
    'c7.f2': 'Oma Hedwig\'s last embroidered ribbon. I brought this one from the stump.',
    'c7.f3': 'My Potato Queen sash.',
    'c7.f4': 'The red thread from Hilde\'s shoe. It was left on the stitching room floor.',
    'c7.f5': 'A strip of taquara from my basket. So the binding belongs to everyone this time.',
    'c7.f6': 'The Kerb ribbon from Linha Esperança.',
    'c7.f7': 'And this one... the little ribbon Dad hung on the mirror in 1977. I\'ve carried it for twenty years.',
    'c7.f7b': '...You kept it.',
    'c7.r1': 'BAPTISM', 'c7.r2': 'OMA HEDWIG', 'c7.r3': 'QUEEN', 'c7.r4': 'HILDE', 'c7.r5': 'TAQUARA', 'c7.r6': 'KERB', 'c7.r7': 'MIRROR',
    'c7.p5': 'Found this in the ballroom, Arno. The Lad\'s lasso. Left lying on the dance floor.',
    'c7.p6': 'Bah... a devil\'s lasso?',
    'c7.p7': 'It was. Now it\'s blessed. Bullets run out, a lasso doesn\'t.',
    'c7.p8': 'And I\'ll be up at the window with my rifle. Shooting King of \'97, boy!',
    'c7.p9': 'Listen... The bell is ringing by itself.',
    'c7.p10': 'He\'s here. Go, boy. We\'ll hold the prayer in here.',
    'c7.p11': 'Arno! ...Come back home, you hear?',
    'c7.p12': 'Keep the water on the stove, Dad. This night ends tonight.',
    'c7.lasso': 'BLESSED LASSO',
    'c7.toll': 'DONG...',

    'hint.lasso': 'V  or  ↑ + X  =  BLESSED LASSO',
    'hint.lasso@touch': '↑ + B  =  BLESSED LASSO',
    'hint.lasso@pad': '{shoot}  or  ↑ + {attack}  =  BLESSED LASSO',
    'c7.hud.lasso': 'LASSO',
    'c7.h1': 'Go, boy! I\'ll cover you from up here!',
    'c7.bang': 'BANG!',
    'c7.b.square': 'The square is overrun... Creatures from every corner of Teewald.',
    'c7.b.cem': 'The colony cemetery. The Beckers are buried here too.',
    'c7.b.door': 'The side door. It goes down to the crypt, under the church.',
    'c7.b.lamp': 'A lantern hanging by the crypt door. This one comes with me.',
    'c7.b.book': 'The logbook of the Hoffnung... Every family signed with an X. Every one but one.',
    'c7.b.tower': 'The tower stairs. The bell is up there... and it won\'t stop ringing.',
    'c7.b.clock': 'The clockwork. The hands are stopped at eleven forty-seven.',
    'c7.b.dark': 'Pitch black... I can\'t even see my own hand.',
    'c7.b.flies': 'Fireflies... The Boitatá\'s light! She didn\'t forget us.',
    'c7.b.bell': 'The Hoffnung\'s bell. It came on the ship in 1852... And down there... he got into the church!',
    'c7.s.matriz': 'MOTHER CHURCH OF SAINT MICHAEL THE ARCHANGEL — 1855. The doors are barred from inside. In there, the town is praying.',
    'c7.s.becker': 'BECKER FAMILY. "Hier ruht in Gott" — here rests in God. There are fresh flowers on Grandpa\'s grave.',
    'c7.s.door': 'CRYPT. Silence: the priests of Teewald rest here.',
    'c7.s.padre': 'FR. ANTÔNIO SCHNEIDER, 1859–1931. He never let the bell ring at midnight. Nobody knew why.',
    'c7.s.stone': 'FOUNDATION STONE OF THE CHURCH — 1855. Under it, in an open iron chest, the logbook.',
    'c7.s.book': 'LOGBOOK OF THE SAILING SHIP HOFFNUNG — 1852. A page of names, each with an X beside it. Below, apart: "Hedwig" — crossed out so angrily the quill tore the paper.',
    'c7.s.tower': 'BELL TOWER. No climbing without the sexton.',
    'c7.s.clock': 'CHURCH CLOCK. A gift from the Shooting Society, 1923.',
    'c7.s.bell': '"HOFFNUNG — 1852". The ship\'s bell, recast in Teewald.',
    'c7.e1a': 'The Cyclops?! I took you down in the square!',
    'c7.e1b': 'No... It\'s just an echo. The fog remembers everything.',
    'c7.e1c': 'Back to the fog where you belong.',
    'c7.e2a': 'Good evening, Becker. Missed the waltz?',
    'c7.e2b': 'You\'re just an echo, Lad.',
    'c7.e2c': 'Echoes dance too.',
    'c7.e2d': '...the last song... is yours...',
    'c7.echo1': 'ECHO: THE GIANT CYCLOPS',
    'c7.echo2': 'ECHO: THE LAD OF THE BALL',
    'c7.hi1': 'A gap... There\'s no jumping that.',
    'c7.hi2': 'You opened my door. I\'ll stitch your way.',
    'c7.hi3': 'Thank you, Hilde.',
    'c7.hi4': 'Now I have the whole night to dance.',
    'en.c7hand': 'LONG HAND',
    'en.c7cyclops': 'CYCLOPS ECHO',
    'en.c7moco': 'LAD\'S ECHO',

    'boss7.name': 'DER ALTE — THE OLD ONE',
    'c7.a1': 'Becker. A hundred and forty-five years I waited for this night.',
    'c7.a2': 'You signed. The wind came. One from every family, every generation.',
    'c7.a3': 'Nobody here signed anything with you.',
    'c7.a4': 'The blood signed. And you gave back everything that was in the ball. The whole debt fell due.',
    'c7.a5': 'Then come and collect.',
    'hint.c7p1': 'HIT THE HANDS!  GET OUT OF THE SHADOW!',
    'hint.c7fog': 'IN THE FOG, WATCH HIS EYES... AND JUMP!',
    'hint.c7grab': 'HE GRABBED SOMEONE!  HIT THE HAND!',
    'hint.c7p2': 'STAY NEAR HEDWIG\'S LANTERN!',
    'hint.c7p3': 'PROTECT THE DANCERS!  HIT THE HANDS!',
    'hint.c7rope': 'PULL THE BELL ROPE!   X  NEAR THE ROPE',
    'hint.c7rope@touch': 'PULL THE BELL ROPE!   B  NEAR THE ROPE',
    'hint.c7rope@pad': 'PULL THE BELL ROPE!   {attack}  NEAR THE ROPE',
    'c7.s1': 'Remember, Hedwig? Forty days of dead calm. The children crying in the hold.',
    'c7.s2': 'The ship... It\'s the hold of the Hoffnung!',
    'c7.s3': 'Now you understand why I didn\'t sign.',
    'c7.s4': 'Stay near my light, boy. He can\'t stand a healer\'s lantern.',
    'c7.s5': 'Oma Hedwig...',
    'c7.d1': 'The rest isn\'t up to me, boy. It\'s up to the town.',
    'c7.d2': 'Now, everyone! To the ribbon pole! Erwin, the waltz!',
    'c7.d3': 'One, two, three... and one, two, three!',
    'c7.tie': 'RIBBON {n}!',
    'c7.grabbed': 'THE DANCE STOPPED!',
    'c7.freed': 'FREED!',
    'c7.heal': 'FEAR FEEDS THE OLD ONE!',
    'c7.dazzle': 'HEDWIG\'S LIGHT!',
    'c7.k1': 'One Becker is missing. Give me the old man and I\'ll let the town go.',
    'c7.k2': 'He\'s right, boy. I\'ve owed for twenty years.',
    'c7.k3': 'Nobody pays anything anymore. Not even you, Dad.',
    'c7.k4': 'The debt belongs to everyone. And no one pays.',
    'c7.k5': 'All together, now. The way Oma Hedwig taught us.',
    'c7.v0': 'Was zusammen gepflanzt ist, wird zusammen gebunden.',
    'c7.v1': 'What was planted together is bound together.',
    'c7.v2': 'What was forgotten is remembered today.',
    'c7.v3': 'And the night that came on the ship',
    'c7.v4': 'goes back to the sea, taking no one.',
    'c7.k6': 'This bell called you in 1852.',
    'c7.k7': 'Now it sends you away.',
    'c7.pull': 'PULL!',
    'c7.c0': '...the sea... again...',
    'c7.c1': 'Morning...',
    'c7.c2': 'Look at the sun coming through the windows, boy.',

    'c7.z1': 'The sun! Everyone, the SUN!',
    'c7.z2': 'I\'m opening the store today. Free beer for everyone!',
    'c7.z3': 'Bah! Never fired so many shots in my life. Not even at the Kerb of \'82.',
    'c7.z4': 'Look... My watch is running.',
    'c7.z5': 'Dad! Your hair...',
    'c7.z6': 'Bah... now I\'m really home.',
    'c7.z7': 'Twenty years all at once. Frida, do you still have that tea for a bad back?',
    'c7.z8': 'And mate for three. Sit down, Ewald. You too, Arno.',
    'c7.ep1': 'Down by the creek, Mr. Gerhard nailed a bronze plaque to the factory gate.',
    'c7.ep2': 'On the hill, the old sign was torn down. And the pine-knot fire stayed lit.',
    'c7.ep2r': 'Now the fire belongs to everyone.',
    'c7.ep3': 'In Linha Esperança the children went back to school, the store opened, and on Sunday someone shouted at the bowling lane:',
    'c7.ep3b': '"Gut Holz!"',
    'c7.ep4': 'May 1998. The 3rd Potato Festival. The girls danced the ribbon pole around a young araucaria Mr. Kessler planted in the stump.',
    'c7.ep4b': 'Now everyone knows why.',
    'c7.yc': 'Mountain Highway — 6:12 AM',
    'c7.y1': 'Dad drove this route every week. And I rode along, just a boy, in the passenger seat.',
    'c7.y2': 'Now I\'m the passenger. And the boy is driving. Bah, what a world.',
    'c7.y3': '...104.5, the mountain radio. Good morning, Teewald. Clear skies all over the mountains.',
    'c7.y4': 'Whistle that waltz, Dad.',
    'c7.y5': 'The one from the ball?',
    'c7.y6': 'The one from the road.',
    'c7.fim': 'THE END',

    'cred7.2': 'A story in seven chapters',
    'cred7.c1': 'Chapter 1 — The Sleeping Town',
    'cred7.c2': 'Chapter 2 — The Ribbon Trail',
    'cred7.c3': 'Chapter 3 — The Ball Beneath the Earth',
    'cred7.c4': 'Chapter 4 — The Last Shift',
    'cred7.c5': 'Chapter 5 — The Great Night',
    'cred7.c6': 'Chapter 6 — The Night of the Pelznickel',
    'cred7.c7': 'Chapter 7 — The Last Ribbon',
    'cred7.leg': 'Legends',
    'cred7.l1': 'der Alte, the Old One, the Long Hand',
    'cred7.l2': 'the ribbon pole and the seven blessed ribbons',
    'cred7.l3': 'the Lad of the Ball and the goat hoof',
    'cred7.l4': 'the Night-Shift Girl',
    'cred7.l5': 'the Boiguaçu and the Boitatá',
    'cred7.l6': 'the Pelznickel and the old man\'s beard',
    'cred7.pla': 'Places',
    'cred7.p1': 'the mountains and the araucarias,',
    'cred7.p2': 'the Santa Bárbara mine, the Morgenstern factory,',
    'cred7.p3': 'the cave on the hill, Linha Esperança',
    'cred7.p4': 'and the church of Saint Michael the Archangel.',
    'cred7.peo': 'The people of Teewald',
    'cred7.g1': 'Arno and Ewald Becker, Dona Frida, Dona Rosa,',
    'cred7.g2': 'Oma Hedwig, Hilde Weber, Ingrid Weber,',
    'cred7.g3': 'Mr. Helmut, Mr. Gerhard, Mr. Arnoldo,',
    'cred7.g4': 'Mr. Kessler, Mr. Erwin and the band, little Lena.',
    'cred7.code': 'Pixel art, music and sound',
    'cred7.code2': 'generated entirely in code',
    'cred7.ded': 'For everyone who still lights the fire in winter.',
    'cred7.thanks': 'Thank you for playing!'
  });
})();
