'use strict';
/* Teewald City — textos em português e inglês */
(function () {
  var L = {};

  L.pt = {
    'boot.press': 'PRESSIONE START',
    'boot.hint': 'ENTER / Z / TOQUE',
    'boot.lang': 'ESCOLHA O IDIOMA',

    'menu.new': 'NOVO JOGO',
    'menu.continue': 'CONTINUAR',
    'menu.options': 'OPÇÕES',
    'menu.controls': 'CONTROLES',
    'title.sub': 'CAPÍTULO 2 — A TRILHA DAS FITAS',
    'title.copy': '© 2026  TEEWALD CITY',

    'opt.title': 'OPÇÕES',
    'opt.lang': 'IDIOMA',
    'opt.crt': 'FILTRO CRT',
    'opt.chroma': 'ABERRAÇÃO CROMÁTICA',
    'opt.aspect': 'PROPORÇÃO',
    'opt.music': 'MÚSICA',
    'opt.sfx': 'EFEITOS',
    'opt.full': 'TELA CHEIA',
    'opt.back': 'VOLTAR',
    'opt.diff': 'DIFICULDADE',
    'diff.title': 'ESCOLHA A DIFICULDADE',
    'diff.easy': 'FÁCIL',
    'diff.normal': 'NORMAL',
    'diff.hard': 'DIFÍCIL',
    'diff.easy.d': 'Para curtir a história. Os golpes tiram metade da energia, um inimigo ataca por vez e você tem 5 vidas.',
    'diff.normal.d': 'Desafio equilibrado. Encostar nos inimigos não machuca, só os ataques deles.',
    'diff.hard.d': 'Como nos fliperamas: todos atacam juntos e até encostar machuca.',
    'diff.change': 'Dá para mudar na pausa a qualquer momento.',
    'on': 'LIGADO',
    'off': 'DESLIGADO',
    'aspect.square': 'PIXEL QUADRADO',
    'aspect.tv': 'TV 4:3',
    'lang.name': 'PORTUGUÊS',

    'ctrl.title': 'CONTROLES',
    'ctrl.move': 'MOVER',
    'ctrl.jump': 'PULAR',
    'ctrl.attack': 'ATACAR / COMBO',
    'ctrl.special': 'GIRO ESPECIAL',
    'ctrl.pause': 'PAUSA',
    'ctrl.read': 'LER PLACAS',
    'ctrl.keys1': 'SETAS / WASD',
    'ctrl.keys2': 'Z / ESPAÇO / K',
    'ctrl.keys3': 'X / J',
    'ctrl.keys4': 'C / L',
    'ctrl.keys5': 'ENTER / ESC',
    'ctrl.keys6': '↑ PERTO DA PLACA',
    'ctrl.pad': 'Controles USB e telas de toque também funcionam.',

    'pause': 'PAUSA',
    'pause.resume': 'CONTINUAR',
    'pause.quit': 'SAIR PARA O TÍTULO',

    'hud.score': 'PONTOS',
    'go': 'SIGA',
    'fight': 'LUTE!',
    'stage1.num': 'FASE 1',
    'stage1.name': 'A CIDADE ADORMECIDA',
    'continue': 'CONTINUAR?',
    'gameover': 'FIM DE JOGO',
    'clear': 'FASE CONCLUÍDA',
    'tally.score': 'PONTOS',
    'tally.time': 'BÔNUS DE TEMPO',
    'tally.hp': 'BÔNUS DE ENERGIA',
    'tally.total': 'TOTAL',
    'checkpoint': 'VELA ACESA',

    'hint.move': '◀ ▶ ANDAR    Z PULAR    X ATACAR',
    'hint.combo': 'X X X  =  COMBO!   PULO + X  =  VOADORA',
    'hint.special': 'C  =  GIRO ESPECIAL (gasta um pouco de energia)',
    'hint.break': 'Quebre caixotes e barris: tem comida dentro!',
    'hint.read': '↑  LER',

    /* variantes para a tela de toque (TC.t usa 'chave@touch' quando o controle virtual está na tela) */
    'boot.hint@touch': 'TOQUE NA TELA',
    'hint.move@touch': '◀ ▶ ANDAR    A PULAR    B ATACAR',
    'hint.combo@touch': 'B B B  =  COMBO!   PULO + B  =  VOADORA',
    'hint.special@touch': 'Y  =  GIRO ESPECIAL (gasta um pouco de energia)',
    'ctrl.keys1@touch': 'DIRECIONAL',
    'ctrl.keys2@touch': 'BOTÃO A',
    'ctrl.keys3@touch': 'BOTÃO B',
    'ctrl.keys4@touch': 'BOTÃO Y',
    'ctrl.keys5@touch': 'START',
    'ctrl.pad@touch': 'Toque nos menus ou use o direcional e o A.',
    'tb.jump': 'PULAR',
    'tb.attack': 'ATACAR',
    'tb.special': 'GIRO',
    'opt.tsize': 'BOTÕES NA TELA',
    'tsize.0': 'PEQUENOS',
    'tsize.1': 'MÉDIOS',
    'tsize.2': 'GRANDES',
    'opt.vibe': 'VIBRAÇÃO',

    /* variantes para quem joga com controle físico ({ação} = nome do botão no controle em uso) */
    'boot.hint@pad': '{start} / {jump}',
    'intro.skip@pad': '{start}: PULAR',
    'cont.hint': 'START / Z',
    'cont.hint@touch': 'START / A',
    'cont.hint@pad': '{start} / {jump}',
    'hint.move@pad': '◀ ▶ ANDAR    {jump} PULAR    {attack} ATACAR',
    'hint.combo@pad': '{attack} {attack} {attack}  =  COMBO!   PULO + {attack}  =  VOADORA',
    'hint.special@pad': '{special}  =  GIRO ESPECIAL (gasta um pouco de energia)',
    'hint.gun@pad': '{shoot}  ou  ↑ + {attack}  =  ATIRAR COM O 38',
    'ctrl.keys1@pad': 'DIRECIONAL / ANALÓGICO',
    'ctrl.keys2@pad': '{jump}',
    'ctrl.keys3@pad': '{attack*}',
    'ctrl.keys4@pad': '{special*}',
    'ctrl.keys5@pad': '{start}',
    'ctrl.keys7@pad': '{shoot} / ↑ + {attack}',
    'ctrl.pad@pad': 'Botões trocados? Vá em OPÇÕES > CONTROLE.',
    'opt.pad': 'CONTROLE (JOYSTICK)',
    'pad.title': 'CONTROLE (JOYSTICK)',
    'pad.none': 'Nenhum controle encontrado.',
    'pad.none2': 'Conecte o controle e aperte um botão dele.',
    'pad.std': 'Botões reconhecidos automaticamente.',
    'pad.custom': 'Botões configurados por você.',
    'pad.gen': 'Modelo desconhecido: configure os botões!',
    'pad.map': 'CONFIGURAR BOTÕES',
    'pad.reset': 'RESTAURAR PADRÃO',
    'pad.test': 'TESTE',
    'pad.shoot': 'TIRO',
    'pad.fam.xbox': 'XBOX',
    'pad.fam.ps': 'PLAYSTATION',
    'pad.fam.nin': 'NINTENDO',
    'pad.fam.gen': 'GENÉRICO',
    'pad.on': 'CONTROLE CONECTADO',
    'pad.off': 'CONTROLE DESCONECTADO',
    'pad.setup': 'Configure em OPÇÕES > CONTROLE',
    'pad.saved': 'CONTROLE CONFIGURADO!',
    'pad.reseted': 'BOTÕES DE FÁBRICA DE VOLTA',
    'pad.cancel': 'CONFIGURAÇÃO CANCELADA',
    'pad.dpad': 'DIRECIONAL',
    'pad.axis': 'EIXO',
    'padmap.title': 'CONFIGURAR BOTÕES',
    'padmap.press': 'APERTE NO CONTROLE:',
    'padmap.release': 'SOLTE OS BOTÕES...',
    'padmap.used': 'ESSE JÁ ESTÁ EM USO!',
    'padmap.skip': 'Não tem esse botão? Espere ',
    'padmap.cancel': 'ESC: CANCELAR',
    'padmap.up': '↑ CIMA',
    'padmap.down': '↓ BAIXO',
    'padmap.left': '◀ ESQUERDA',
    'padmap.right': '▶ DIREITA',
    'padmap.jump': 'PULAR',
    'padmap.attack': 'ATACAR',
    'padmap.special': 'GIRO ESPECIAL',
    'padmap.shoot': 'REVÓLVER',
    'padmap.start': 'START (PAUSA)',

    'item.cuca': 'CUCA',
    'item.linguica': 'LINGUIÇA',
    'item.chimarrao': 'CHIMARRÃO',
    'item.chopp': 'CHOPP',
    'item.bolinho': 'BOLINHO DE BATATA',
    'item.medalha': 'MEDALHA DE SÃO CRISTÓVÃO',
    'item.1up': '1 VIDA!',

    'en.ghost': 'ASSOMBRAÇÃO',
    'en.flame': 'CABEÇA-DE-FOGO',
    'en.shade': 'VULTO',
    'en.crow': 'CORVO',
    'en.crate': 'CAIXOTE',
    'en.barrel': 'BARRIL',
    'boss.name': 'O CICLOPE GIGANTE',

    'name.arno': 'ARNO',
    'name.radio': 'RÁDIO',
    'name.voice': '???',
    'name.frida': 'DONA FRIDA',

    'intro.skip': 'START: PULAR',
    'intro.place': 'Sul do Brasil',
    'intro.date': 'Outono de 1997',
    'intro.road': 'Rodovia da Serra — 23h47',
    'intro.d1': 'Teewald City... Faz vinte anos que eu não subo essa serra.',
    'intro.d2': 'Meu pai fazia essa rota toda semana. E eu ia junto, guri ainda, no banco do carona.',
    'intro.d3': 'Olha essas araucárias... Tem umas aí que já eram velhas antes do primeiro colono chegar.',
    'intro.d4': 'Em noite de lua cheia, a cidade brilhava lá embaixo. As casas de enxaimel, a torre da igreja...',
    'intro.d5': 'Cheiro de batata assada, a Festa da Batata, a bandinha tocando na praça... Era a cidade mais bonita do mundo.',
    'intro.r1': '...ksshh... atenção, motoristas... kssh... neblina densa na serra...',
    'intro.r2': '...kshh... não... NÃO entrem em Teewald... kssshhh...',
    'intro.d6': 'Hã? ...Rádio velho. Nessa serra só pega chiado.',
    'intro.d7': 'Que neblina é essa, meu Deus... Não enxergo um palmo na frente.',
    'intro.d8': 'Calma, Arno. Devagar. Já tá chegando...',

    'wake.1': '...Hã...?',
    'wake.2': 'Ai... minha cabeça...',
    'wake.3': 'Cadê o caminhão? Eu tava descendo a serra... e agora...',
    'wake.4': 'Essas casas de enxaimel... a torre da igreja... É Teewald City. Tá igualzinha a como eu lembrava.',
    'wake.5': 'Mas cadê todo mundo? Nenhuma janela acesa... nenhum cachorro latindo...',
    'wake.6': '...Mas o que diabos é aquilo?!',

    'mid.bridge': 'O arroio... Meu pai me ensinou a pescar aqui embaixo.',
    'mid.cemetery': 'O cemitério da colônia... Velas acesas? Quem acendeu essas velas?',
    'mid.square': 'A praça da igreja. O sino... Tem alguém lá dentro?',

    'sign.welcome': 'BEM-VINDO A TEEWALD CITY\nFundada em 1852 por colonos do Reno.\n"Willkommen!"',
    'sign.festa': 'FESTA DA BATATA — 2ª EDIÇÃO\nBaile, bandinha e a Rainha da Batata.\nTodos os fins de semana de maio de 1997.',
    'sign.missing': 'DESAPARECIDOS DESDE A NEBLINA:\nfamílias Schmitt, Kessler, Weber...\n(o resto do papel está rasgado)',
    'sign.bridge': 'PONTE DO ARROIO\nCuidado: tábuas soltas.',
    'sign.cemetery': 'CEMITÉRIO DA COLÔNIA\n"Aqui descansam os que vieram de longe."',
    'sign.bakery': 'PADARIA WEBER\nCuca de uva, de banana e de farofa.\nFechado.',

    'boss.1': 'Mas que bicho é esse...?!',
    'boss.2': 'Tá bom, feioso. Vem!',

    'end.1': 'Acabou...?',
    'end.2': 'Arno... Arno Becker.',
    'end.3': 'Quem tá aí? Como sabe o meu nome?',
    'end.4': 'Eu te benzi quando tu era guri. Tu tinha medo do escuro, lembra?',
    'end.5': '...Dona Frida? A benzedeira? Mas a senhora...',
    'end.6': 'Desde a última Festa da Batata, em maio, a noite não acaba mais em Teewald. Eles vieram com a neblina.',
    'end.7': 'E a cidade esperou. Esperou alguém que tivesse coragem de voltar.',
    'end.8': 'Entra, guri. Rápido. Eles estão vindo.',
    'end.9': '...Ah, mas que beleza.',
    'end.chapter': 'FIM DO CAPÍTULO 1',
    'end.tbc': 'Continua...',

    'cred.1': 'TEEWALD CITY',
    'cred.2': 'Capítulo 1 — A Cidade Adormecida',
    'cred.3': 'Pixel art, música e efeitos',
    'cred.4': 'gerados inteiramente em código',
    'cred.5': 'Inspirado na serra do sul do Brasil,',
    'cred.6': 'nas araucárias, nas casas de enxaimel',
    'cred.7': 'e nas histórias contadas à beira do fogão.',
    'cred.8': 'Obrigado por jogar!',

    /* ================= CAPÍTULO 2 — A TRILHA DAS FITAS ================= */
    'menu.chapters': 'CAPÍTULOS',
    'chap.title': 'ESCOLHA O CAPÍTULO',
    'chap.1': '1 — A CIDADE ADORMECIDA',
    'chap.2': '2 — A TRILHA DAS FITAS',
    'chap.1.d': 'Arno volta a Teewald depois de vinte anos e acorda numa cidade vazia, tomada por criaturas.',
    'chap.2.d': 'Dona Frida conta a lenda do Antigo. Arno sai para caçar o demônio, seguindo as fitas bentas.',
    'stage2.num': 'FASE 2',
    'stage2.name': 'A TRILHA DAS FITAS',
    'mission': 'MISSÃO',
    'mission.2': 'Encontre o Mão-Comprida antes que a lua se ponha. Siga as sete fitas bentas.',
    'hint.gun': 'V  ou  ↑ + X  =  ATIRAR COM O 38',
    'hint.gun@touch': '↑ + B  =  ATIRAR COM O 38',
    'hint.boss2': 'PULE A INVESTIDA!  SAIA DA SOMBRA DO SALTO!',
    'gun.empty': 'SEM BALAS!',
    'gun.bullets': 'BALAS',
    'item.balas': 'CAIXA DE BALAS',
    'item.revolver': 'REVÓLVER 38',
    'ctrl.shoot': 'REVÓLVER (CAP. 2)',
    'ctrl.keys7': 'V / ↑ + X',
    'ctrl.keys7@touch': '↑ + B',
    'en.colono': 'POSSUÍDO',
    'en.colona': 'POSSUÍDA',
    'en.kessler': 'SEU KESSLER',
    'en.wolf': 'LOBISOMEM',
    'en.sack': 'SACO DE BATATA',
    'boss2.name': 'O DEMÔNIO ANTIGO',
    'freed.m': 'LIBERTO!',
    'freed.f': 'LIBERTA!',
    'name.kessler': 'SEU KESSLER',
    'name.fita': 'FITA BENTA',
    'name.demon': 'DER ALTE',

    'ch2.card1': 'Teewald City — a mesma noite',
    'ch2.card2': 'Igreja Matriz — a noite que não termina',
    'p2.1': 'Toma um chimarrão, guri. Pra esquentar a alma. Lá fora ninguém mais acende fogo.',
    'p2.2': 'Bah... vinte anos sem um mate de verdade. Amargo que só, Dona Frida.',
    'p2.3': 'Amargo é o que anda lá fora. Escuta bem, que essa história eu só conto uma vez.',
    'p2.l1': 'Em 1852 os nossos avós atravessaram o mar num veleiro. Vinham do Hunsrück, lá na Renânia, com a Bíblia, a enxada e um saco de batata-semente.',
    'p2.l2': 'Mas no porão vinha mais alguém. Lá na Alemanha chamavam de der Alte, o Antigo: um bicho que anda de quatro pela estrada do mato, em noite de cerração, e leva quem anda sozinho.',
    'p2.l3': 'Aqui na serra ele achou o que queria: mato fechado, cerração e gente sozinha. Até que a minha bisavó Hedwig, a primeira benzedeira de Teewald, amarrou ele nas raízes do Pinheiro Velho.',
    'p2.l4': 'A araucária mais antiga de Teewald. Sete fitas bentas e uma reza. Os ervateiros, que tinham visto o bicho no meio da erva, deram outro nome pra ele: o Mão-Comprida.',
    'p2.l5': 'Pra amarração não afrouxar, todo mês de maio as moças dançavam o pau-de-fita em volta do Pinheiro Velho. Cada volta trançava as fitas. Cada fita, um nó.',
    'p2.l6': 'Com os anos, ninguém mais lembrava por quê. Virou festa, com bandinha, chopp e rainha. Só as benzedeiras guardaram o segredo.',
    'p2.l7': 'Esse ano o Kessler da serraria derrubou o Pinheiro Velho pra fazer as tábuas do pavilhão novo da Festa da Batata. Madeira de lei, dava um dinheirão.',
    'p2.l8': 'Dançaram o pau-de-fita num mastro de eucalipto, lá na praça. Não amarrou nada.',
    'p2.l9': 'Naquela mesma noite veio a cerração. O Antigo saiu do toco de quatro, com as fitas ainda enroscadas no couro. E a noite nunca mais acabou.',
    'p2.4': 'E a reza? A senhora sabe a reza da sua bisavó?',
    'p2.5': 'A Oma Hedwig levou a reza pro túmulo. Mas ela bordou cada verso numa das fitas, em ponto de cruz, pra não esquecer.',
    'p2.6': 'O bicho anda ferido por Teewald, perdendo fita pelo caminho. Segue as fitas, Arno. Elas te levam até ele, e te dão a reza inteira.',
    'p2.7': 'Caçar um demônio com um terço e uma cuia de chimarrão... O meu pai ia rir da minha cara.',
    'p2.8': 'Não só com isso. Achei na curva da serra, jogado no meio do mato. Tava no porta-luvas do teu caminhão.',
    'p2.9': 'O meu 38! ...E o caminhão, Dona Frida?',
    'p2.10': 'Do caminhão, nem sinal. Benzi o revólver: bala de arma benta pega em bicho que bala comum não pega. Na Sociedade de Tiro ainda deve ter munição.',
    'p2.11': 'Ele volta pro toco do Pinheiro Velho antes de a lua descer. É lá que tu acaba com isso. Vai com Deus, guri.',
    'p2.12': 'Deixa a água no fogo, Dona Frida. Eu já volto pra segunda cuia.',

    'b2.pavilion': 'O pavilhão novo da Festa... Ainda tem cheiro de resina. É o Pinheiro Velho, cortado em tábua.',
    'b2.mill': 'A atafona dos Weber. A roda ainda gira... sozinha. Ninguém mais pra moer o milho.',
    'b2.sawmill': 'A serraria do Kessler. O pai descarregava tora aqui, e eu ficava brincando no monte de serragem.',
    'b2.fnm': 'Um Fenemê carregado de pinheiro... Igualzinho ao do pai. Ele chamava o dele de Velho Vermelho.',
    'b2.ervateira': 'A ervateira dos Becker. Era do meu avô. Alguém acendeu o carijó... Sente o cheiro de erva sapecada?',
    'b2.clearing': 'Lá no fundo, no meio da clareira... o toco do Pinheiro Velho. As fitas tão tremendo no meu bolso.',
    'tz.1': 'Ali, em cima das toras! O Mão-Comprida...!',
    'tz.2': 'Pode correr, bicho. As tuas fitas tão ficando todas comigo.',

    'rib.count': 'FITA %n DE 7, bordada à mão:',
    'rib.v0': 'Pinheiro velho, raiz de ferro,',
    'rib.v1': 'segura no fundo quem veio do inferno.',
    'rib.v2': 'Na cerração tu chegou,',
    'rib.v3': 'na fita benta tu ficou.',
    'rib.v4': 'Sete fitas, sete nós:',
    'rib.v5': 'volta pra terra e deixa nós.',
    'rib.v6': 'Im Namen Gottes. Amen.',
    'rib.first': 'Ponto de cruz, igual ao das toalhas de mesa da minha vó. É um verso da reza!',
    'rib.mid': 'Metade da reza. Dá pra sentir o bicho perto... a fita fica quente na mão.',
    'rib.last': 'Em alemão... A minha vó rezava assim. Sete fitas, a reza inteira. Agora sim, Mão-Comprida.',

    'k.1': 'Gott im Himmel... A serra... eu não conseguia parar a serra...',
    'k.2': 'Seu Kessler? Sou eu, o Arno. O guri do Becker, do caminhão de tora.',
    'k.3': 'O guri do Becker... Fui eu, Arno. Eu derrubei o Pinheiro Velho. Pagaram bem pela madeira, e o pavilhão novo ia ficar tão bonito...',
    'k.4': 'Na mesma noite ele saiu do toco, de quatro, com as fitas do pau-de-fita enroscadas no couro. E me botou pra serrar tábua sem parar, dia e noite. Só que não tem mais dia.',
    'k.5': 'Escuta: ele corre de quatro feito boi brabo. Pula por cima e bate quando ele der com a cabeça no tronco. E quando ele se agachar, sai de baixo, que ele salta!',
    'k.6': 'Toma. Isso caiu do couro dele quando passou por aqui. Ficou enroscado na serragem.',
    'k.7': 'Vai pra igreja, Seu Kessler. A Dona Frida tá lá, com o chimarrão quente.',
    'k.8': 'Arno... o teu pai. Em 77, numa noite de cerração, o caminhão dele apareceu parado na porteira da ervateira. Vazio. Com o motor ligado.',
    'k.9': '...Disseram que ele caiu na ribanceira.',
    'k.10': 'Disseram.',

    'boss2.a1': 'O toco do Pinheiro Velho... Ele tem que voltar pra cá. Eu espero.',
    'boss2.d1': 'Becker... Der Bub vom Becker.',
    'boss2.d2': 'Tu tem o cheiro do teu pai, guri. Ele também veio sozinho, numa noite de cerração.',
    'boss2.a2': '...O que tu sabe do meu pai?!',
    'boss2.a3': 'Chega de conversa, Mão-Comprida. Hoje tu volta pro buraco.',
    'bind.1': 'Oma Hedwig, me empresta a tua reza...',
    'bind.2': 'Pronto, Dona Frida. Amarrado de novo. Agora é só esperar o dia clarear.',

    'e2.1': 'Acabou. O bicho virou cinza e entrou no toco.',
    'e2.2': '...Mas cadê o dia? A lua não se mexeu um palmo.',
    'e2.3': 'Música...? Uma bandinha. Vem lá de baixo... de dentro do toco!',
    'e2.4': 'Prost! Saúde! Mais um chopp pra mesa do Weber!',
    'e2.5': 'Toca a valsa, Erwin! A Rainha da Batata ainda não dançou!',
    'e2.6': 'Arno! Ô, Arno! Desce, guri! A bandinha tá tocando a nossa valsa!',
    'e2.7': '...Pai?',
    'end2.chapter': 'FIM DO CAPÍTULO 2',
    'end2.next': 'Capítulo 3: O Baile Debaixo da Terra',
    'cred2.2': 'Capítulo 2 — A Trilha das Fitas',
    'cred2.3': 'Lendas, costumes e lugares',
    'cred2.4': 'o pau-de-fita, a benzedeira, o carijó,',
    'cred2.5': 'a atafona, a serraria e o Fenemê,',
    'cred2.6': 'o chimarrão e a Festa da Batata.',

    'sign2.brewery': 'CERVEJARIA SCHMITT — DESDE 1923\nChopp colonial, claro e escuro.\n"Ein Prosit!" Fechado até segunda ordem.',
    'sign2.tiro': 'SOCIEDADE DE TIRO TEEWALD — 1898\nRei do Tiro 1997: Helmut Weber.\nMunição guardada no depósito.',
    'sign2.rainha': 'RAINHA DA BATATA 1997: Ingrid Weber.\nPrincesas: Elke Schmitt e Rosi Kessler.\nBaile com a Bandinha do Erwin.',
    'sign2.missing2': 'ALGUÉM VIU A FAMÍLIA KESSLER?\nA serraria não para de funcionar,\nmas ninguém entra nem sai de lá.',
    'sign2.pavilion': 'PAVILHÃO DA FESTA DA BATATA\nObra da Serraria Kessler.\nMadeira de lei: 100% pinheiro.',
    'sign2.mill': 'ATAFONA DOS WEBER\nFubá, farinha de milho e de mandioca.\nMoída com a água do arroio.',
    'sign2.sawmill': 'SERRARIA KESSLER\nCompra-se pinheiro em pé.\nPaga-se à vista.',
    'sign2.ervateira': 'ERVATEIRA BECKER — DESDE 1889\nErva sapecada no carijó\ne cancheada à moda antiga.',
    'sign2.stump': 'Tábua velha, entalhada a canivete:\n"HIER WIRD NICHT GEHAUEN — 1852"\n(Aqui não se corta.)',

    /* ================= CAPÍTULO 3 — O BAILE DEBAIXO DA TERRA ================= */
    'chap.3': '3 — O BAILE DEBAIXO DA TERRA',
    'chap.3.d': 'Arno desce pela escada do toco até o salão onde os sumidos de Teewald ainda dançam. Lá embaixo está o pai dele.',
    'stage3.num': 'FASE 3',
    'stage3.name': 'O BAILE DEBAIXO DA TERRA',
    'mission3.2': 'Desça até o salão do baile e traga o teu pai de volta lá pra cima.',
    'hint.boss3': 'PULE O LAÇO, A BOLEADEIRA E O RODOPIO!',
    'm.fast': 'Toca mais ligeiro, Erwin!',
    'm.dodge': 'Opa!',
    'en.miner': 'MINEIRO',
    'en.bat': 'MORCEGO',
    'en.dancer': 'DANÇARINOS',
    'en.cart': 'VAGONETE',
    'boss3.name': 'O MOÇO DO BAILE',
    'freed.p': 'LIBERTOS!',
    'name.ewald': 'EWALD BECKER',
    'name.moco': 'O MOÇO DO BAILE',
    'name.ingrid': 'INGRID WEBER',
    'ch3.card1': 'Debaixo do toco do Pinheiro Velho',
    'ch3.card2': 'Uma escada que não estava em mapa nenhum',
    'p3.1': 'Uma escada de pedra, dentro de um toco de árvore... Isso aqui é mais velho que a cidade.',
    'p3.2': 'Prost! Saúde! Mais uma rodada pra mesa dos Weber!',
    'p3.3': 'Tem nome riscado nos degraus, a canivete. Schmitt, 1898... Weber, 1931... Kessler, 1997...',
    'p3.4': '...Becker, 1977.',
    'p3.5': 'Aguenta firme, pai. Eu tô descendo.',
    'b3.lamp': 'Uma lamparina de carbureto pendurada no fim da escada... Ainda acende. Bah, melhor que nada.',
    'b3.roots': 'As raízes do Pinheiro Velho. Descem até onde a vista não alcança.',
    'b3.mine': 'Uma mina de carvão debaixo de Teewald? O vô falava de uma mina que desabou em 31, com doze homens lá dentro. Ninguém acreditava.',
    'b3.barbara': 'Santa Bárbara, a padroeira dos mineiros. Alguém ainda acende vela pra ela aqui embaixo.',
    'b3.lift': 'O elevador de carga da mina. Se eu descer, não tem volta... Bah, já cheguei até aqui.',
    'b3.cave': 'Uma gruta... E lá no fundo, a valsa. Cada vez mais alta.',
    'b3.ballroom': 'Mãe do céu... É a Festa. Toda a gente que sumiu, dançando debaixo da terra.',
    'b3.stage': 'Lá no meio da pista... um moço de chapéu preto, dançando com a Rainha da Batata.',
    'fa.1': 'Pai...? PAI!',
    'fa.2': '...um, dois, três... um, dois, três... Que valsa bonita, Erwin. Toca de novo.',
    'fa.3': 'Pai, sou eu! O Arno! Olha pra mim!',
    'fa.4': 'Quem não dança não fica no baile.',
    'fa.5': 'Então eu danço do meu jeito.',
    'm.1': 'Boa noite, Becker. Chegou bem na hora da valsa.',
    'm.2': 'Quem é tu?',
    'm.3': 'Lá no Hunsrück me chamavam de Tanzteufel. Aqui na serra me chamam de Moço do Baile. Em toda festa aparece um moço bonito que ninguém convidou.',
    'm.4': 'O teu pai dançou comigo em 77. Bom pé de valsa, o Ewald. E tu veio sozinho, igual a ele.',
    'm.4b': 'Gostou da voz lá de cima? "Desce, guri!" Eu imito qualquer um que já dançou comigo.',
    'm.5': 'Solta o meu pai. Solta todo mundo.',
    'm.6': 'Ninguém sai da pista antes da última música. E a última quem toca sou eu.',
    'm.8': 'Ninguém... nunca... olhou pros meus pés...',
    'm.9': 'Pé de bode. A vó sempre dizia: no baile, antes de dançar com moço bonito, olha o pé dele.',
    'e3.1': 'Onde é que a gente tá? A Festa... a gente tava dançando no pavilhão...',
    'e3.2': 'Arno? ...Mas tu tá um homem feito. E de bigode, igualzinho ao teu vô.',
    'e3.3': 'Pai... Faz vinte anos.',
    'e3.4': 'Vinte anos? Eu desci só pra buscar o Erwin, que tinha sumido na ervateira. Era pra ser cinco minutos. Deixei até o motor do caminhão ligado.',
    'e3.5': 'O meu relógio parou... Onze e quarenta e sete.',
    'e3.6': 'Foi a hora em que eu perdi o caminhão na serra.',
    'e3.7': 'Então foi ele que te chamou pra cá. Me perdoa, guri.',
    'e3.8': 'Vamos pra casa, pai. A Dona Frida deixou a água no fogo.',
    'e3.9': 'Eu disse que deixava a água no fogo.',
    'e3.10': 'Frida? Bah, mas tu tá velha!',
    'e3.11': 'E tu tá vinte anos atrasado, Ewald Becker. Toma um mate.',
    'e3.12': 'Olha, pai. O sol.',
    'e3.cap': 'A primeira manhã em Teewald desde a Festa da Batata.',
    'e3.r1': '...ksshh... 104,5, a rádio da serra... o baile acabou... ksshh... mas a cerração... ksshh... ainda não foi toda embora...',
    'end3.chapter': 'FIM DO CAPÍTULO 3',
    'cred3.2': 'Capítulo 3 — O Baile Debaixo da Terra',
    'cred3.3': 'Lendas, costumes e lugares',
    'cred3.4': 'o Moço do Baile e o pé de bode,',
    'cred3.5': 'a mina de carvão e Santa Bárbara,',
    'cred3.6': 'a bandinha, o kerb e a valsa do pai.',
    'sign3.board': 'Tábua pregada na parede:\n"QUEM DESCE PRO BAILE NÃO SOBE\nANTES DA ÚLTIMA MÚSICA."',
    'sign3.mine': 'MINA SANTA BÁRBARA\nCompanhia Carbonífera de Teewald — 1904.\nFechada depois do desabamento de 1931.',
    'sign3.grisu': 'PERIGO: GRISU\nNão acender fósforo nem lampião\nsem ordem do capataz.',
    'sign3.barbara': 'Santa Bárbara, protetora dos mineiros,\nlivrai-nos do raio, do fogo e do desabamento.\n(Doze nomes riscados embaixo.)',
    'sign3.lift': 'ELEVADOR DE CARGA\nCapacidade: 2 vagonetes ou 8 homens.\nFavor não pular com ele andando.',
    'sign3.river': 'Escrito a giz na pedra:\n"O RIO ESCURO NÃO TEM FUNDO."\n— os mineiros de 31',
    'sign3.ballroom': 'BAILE DE KERB — ENTRADA FRANCA\nTraje: o de domingo.\nBandinha do Erwin, tocando desde 1852.',
    'sign3.queen': 'RAINHAS DO BAILE: Lotte Schmitt (1898),\nHilda Weber (1931), Irmgard Kessler (1977)\ne Ingrid Weber (1997).'
  };

  L.en = {
    'boot.press': 'PRESS START',
    'boot.hint': 'ENTER / Z / TAP',
    'boot.lang': 'CHOOSE LANGUAGE',

    'menu.new': 'NEW GAME',
    'menu.continue': 'CONTINUE',
    'menu.options': 'OPTIONS',
    'menu.controls': 'CONTROLS',
    'title.sub': 'CHAPTER 2 — THE RIBBON TRAIL',
    'title.copy': '© 2026  TEEWALD CITY',

    'opt.title': 'OPTIONS',
    'opt.lang': 'LANGUAGE',
    'opt.crt': 'CRT FILTER',
    'opt.chroma': 'CHROMATIC ABERRATION',
    'opt.aspect': 'ASPECT',
    'opt.music': 'MUSIC',
    'opt.sfx': 'SOUND FX',
    'opt.full': 'FULLSCREEN',
    'opt.back': 'BACK',
    'opt.diff': 'DIFFICULTY',
    'diff.title': 'CHOOSE DIFFICULTY',
    'diff.easy': 'EASY',
    'diff.normal': 'NORMAL',
    'diff.hard': 'HARD',
    'diff.easy.d': 'Enjoy the story. Hits take half the health, one enemy attacks at a time and you get 5 lives.',
    'diff.normal.d': 'A balanced challenge. Touching enemies is safe; only their attacks hurt.',
    'diff.hard.d': 'Arcade-tough: everyone attacks at once and even a touch hurts.',
    'diff.change': 'Change it anytime from the pause menu.',
    'on': 'ON',
    'off': 'OFF',
    'aspect.square': 'SQUARE PIXELS',
    'aspect.tv': 'TV 4:3',
    'lang.name': 'ENGLISH',

    'ctrl.title': 'CONTROLS',
    'ctrl.move': 'MOVE',
    'ctrl.jump': 'JUMP',
    'ctrl.attack': 'ATTACK / COMBO',
    'ctrl.special': 'SPIN SPECIAL',
    'ctrl.pause': 'PAUSE',
    'ctrl.read': 'READ SIGNS',
    'ctrl.keys1': 'ARROWS / WASD',
    'ctrl.keys2': 'Z / SPACE / K',
    'ctrl.keys3': 'X / J',
    'ctrl.keys4': 'C / L',
    'ctrl.keys5': 'ENTER / ESC',
    'ctrl.keys6': '↑ NEAR A SIGN',
    'ctrl.pad': 'USB gamepads and touch screens work too.',

    'pause': 'PAUSED',
    'pause.resume': 'RESUME',
    'pause.quit': 'QUIT TO TITLE',

    'hud.score': 'SCORE',
    'go': 'GO',
    'fight': 'FIGHT!',
    'stage1.num': 'STAGE 1',
    'stage1.name': 'THE SLEEPING TOWN',
    'continue': 'CONTINUE?',
    'gameover': 'GAME OVER',
    'clear': 'STAGE CLEAR',
    'tally.score': 'SCORE',
    'tally.time': 'TIME BONUS',
    'tally.hp': 'HEALTH BONUS',
    'tally.total': 'TOTAL',
    'checkpoint': 'CANDLE LIT',

    'hint.move': '◀ ▶ WALK    Z JUMP    X ATTACK',
    'hint.combo': 'X X X  =  COMBO!   JUMP + X  =  FLYING KICK',
    'hint.special': 'C  =  SPIN SPECIAL (costs a little health)',
    'hint.break': 'Smash crates and barrels: there is food inside!',
    'hint.read': '↑  READ',

    'boot.hint@touch': 'TAP THE SCREEN',
    'hint.move@touch': '◀ ▶ WALK    A JUMP    B ATTACK',
    'hint.combo@touch': 'B B B  =  COMBO!   JUMP + B  =  FLYING KICK',
    'hint.special@touch': 'Y  =  SPIN SPECIAL (costs a little health)',
    'ctrl.keys1@touch': 'D-PAD',
    'ctrl.keys2@touch': 'A BUTTON',
    'ctrl.keys3@touch': 'B BUTTON',
    'ctrl.keys4@touch': 'Y BUTTON',
    'ctrl.keys5@touch': 'START',
    'ctrl.pad@touch': 'Tap the menus or use the D-pad and A.',
    'tb.jump': 'JUMP',
    'tb.attack': 'ATTACK',
    'tb.special': 'SPIN',
    'opt.tsize': 'TOUCH BUTTONS',
    'tsize.0': 'SMALL',
    'tsize.1': 'MEDIUM',
    'tsize.2': 'LARGE',
    'opt.vibe': 'VIBRATION',

    'boot.hint@pad': '{start} / {jump}',
    'intro.skip@pad': '{start}: SKIP',
    'cont.hint': 'START / Z',
    'cont.hint@touch': 'START / A',
    'cont.hint@pad': '{start} / {jump}',
    'hint.move@pad': '◀ ▶ WALK    {jump} JUMP    {attack} ATTACK',
    'hint.combo@pad': '{attack} {attack} {attack}  =  COMBO!   JUMP + {attack}  =  FLYING KICK',
    'hint.special@pad': '{special}  =  SPIN SPECIAL (costs a little health)',
    'hint.gun@pad': '{shoot}  or  ↑ + {attack}  =  FIRE THE .38',
    'ctrl.keys1@pad': 'D-PAD / STICK',
    'ctrl.keys2@pad': '{jump}',
    'ctrl.keys3@pad': '{attack*}',
    'ctrl.keys4@pad': '{special*}',
    'ctrl.keys5@pad': '{start}',
    'ctrl.keys7@pad': '{shoot} / ↑ + {attack}',
    'ctrl.pad@pad': 'Buttons mixed up? Go to OPTIONS > GAMEPAD.',
    'opt.pad': 'GAMEPAD',
    'pad.title': 'GAMEPAD',
    'pad.none': 'No gamepad found.',
    'pad.none2': 'Plug it in and press one of its buttons.',
    'pad.std': 'Buttons recognized automatically.',
    'pad.custom': 'Buttons set up by you.',
    'pad.gen': 'Unknown model: set up the buttons!',
    'pad.map': 'SET UP BUTTONS',
    'pad.reset': 'RESTORE DEFAULTS',
    'pad.test': 'TEST',
    'pad.shoot': 'SHOOT',
    'pad.fam.xbox': 'XBOX',
    'pad.fam.ps': 'PLAYSTATION',
    'pad.fam.nin': 'NINTENDO',
    'pad.fam.gen': 'GENERIC',
    'pad.on': 'GAMEPAD CONNECTED',
    'pad.off': 'GAMEPAD DISCONNECTED',
    'pad.setup': 'Set it up in OPTIONS > GAMEPAD',
    'pad.saved': 'GAMEPAD SET UP!',
    'pad.reseted': 'FACTORY BUTTONS RESTORED',
    'pad.cancel': 'SETUP CANCELED',
    'pad.dpad': 'D-PAD',
    'pad.axis': 'AXIS',
    'padmap.title': 'SET UP BUTTONS',
    'padmap.press': 'PRESS ON THE GAMEPAD:',
    'padmap.release': 'RELEASE THE BUTTONS...',
    'padmap.used': 'THAT ONE IS TAKEN!',
    'padmap.skip': 'No such button? Wait ',
    'padmap.cancel': 'ESC: CANCEL',
    'padmap.up': '↑ UP',
    'padmap.down': '↓ DOWN',
    'padmap.left': '◀ LEFT',
    'padmap.right': '▶ RIGHT',
    'padmap.jump': 'JUMP',
    'padmap.attack': 'ATTACK',
    'padmap.special': 'SPIN SPECIAL',
    'padmap.shoot': 'REVOLVER',
    'padmap.start': 'START (PAUSE)',

    'item.cuca': 'STREUSEL CAKE',
    'item.linguica': 'SAUSAGE',
    'item.chimarrao': 'YERBA MATE',
    'item.chopp': 'DRAFT BEER',
    'item.bolinho': 'POTATO CROQUETTE',
    'item.medalha': 'ST. CHRISTOPHER MEDAL',
    'item.1up': '1 UP!',

    'en.ghost': 'HAUNT',
    'en.flame': 'FLAMEHEAD',
    'en.shade': 'SHADE',
    'en.crow': 'CROW',
    'en.crate': 'CRATE',
    'en.barrel': 'BARREL',
    'boss.name': 'THE GIANT CYCLOPS',

    'name.arno': 'ARNO',
    'name.radio': 'RADIO',
    'name.voice': '???',
    'name.frida': 'DONA FRIDA',

    'intro.skip': 'START: SKIP',
    'intro.place': 'Southern Brazil',
    'intro.date': 'Late autumn, 1997',
    'intro.road': 'Highland Road — 11:47 PM',
    'intro.d1': 'Teewald City... Twenty years since I last drove up this range.',
    'intro.d2': 'My father ran this route every week. I rode along, just a kid, in the passenger seat.',
    'intro.d3': 'Look at those araucarias... Some of them were already old before the first settlers came.',
    'intro.d4': 'On full-moon nights the town glowed down below. The half-timbered houses, the church tower...',
    'intro.d5': 'The smell of roast potatoes, the Potato Festival, the little band playing in the square... The most beautiful town in the world.',
    'intro.r1': '...ksshh... attention, drivers... kssh... thick fog on the range...',
    'intro.r2': '...kshh... do not... do NOT enter Teewald... kssshhh...',
    'intro.d6': 'Huh? ...Old radio. Nothing but static up here.',
    'intro.d7': 'Good Lord, where did this fog come from... I can\'t see a thing.',
    'intro.d8': 'Easy, Arno. Slow down. Almost there...',

    'wake.1': '...Huh...?',
    'wake.2': 'Ugh... my head...',
    'wake.3': 'Where\'s the truck? I was coming down the range... and now...',
    'wake.4': 'These half-timbered houses... the church tower... It\'s Teewald City. Just like I remember it.',
    'wake.5': 'But where is everyone? Not a single window lit... not even a dog barking...',
    'wake.6': '...What the hell is that?!',

    'mid.bridge': 'The creek... My father taught me to fish down there.',
    'mid.cemetery': 'The old settlers\' cemetery... Lit candles? Who lit all these candles?',
    'mid.square': 'The church square. The bell... Is someone in there?',

    'sign.welcome': 'WELCOME TO TEEWALD CITY\nFounded in 1852 by settlers from the Rhine.\n"Willkommen!"',
    'sign.festa': 'POTATO FESTIVAL — 2ND EDITION\nDance, brass band and the Potato Queen.\nEvery weekend in May, 1997.',
    'sign.missing': 'MISSING SINCE THE FOG:\nthe Schmitt, Kessler, Weber families...\n(the rest of the paper is torn)',
    'sign.bridge': 'CREEK BRIDGE\nCareful: loose planks.',
    'sign.cemetery': 'SETTLERS\' CEMETERY\n"Here rest those who came from afar."',
    'sign.bakery': 'WEBER BAKERY\nStreusel cakes: grape, banana and plain crumb.\nClosed.',

    'boss.1': 'What in God\'s name is that...?!',
    'boss.2': 'Alright, ugly. Bring it!',

    'end.1': 'Is it... over?',
    'end.2': 'Arno... Arno Becker.',
    'end.3': 'Who\'s there? How do you know my name?',
    'end.4': 'I blessed you when you were a boy. You were afraid of the dark, remember?',
    'end.5': '...Dona Frida? The old healer? But you...',
    'end.6': 'Ever since the last Potato Festival in May, the night has never ended in Teewald. They came with the fog.',
    'end.7': 'And the town waited. Waited for someone brave enough to come back.',
    'end.8': 'Come inside, boy. Quickly. They\'re coming.',
    'end.9': '...Oh, just wonderful.',
    'end.chapter': 'END OF CHAPTER 1',
    'end.tbc': 'To be continued...',

    'cred.1': 'TEEWALD CITY',
    'cred.2': 'Chapter 1 — The Sleeping Town',
    'cred.3': 'Pixel art, music and sound',
    'cred.4': 'generated entirely in code',
    'cred.5': 'Inspired by the highlands of southern Brazil,',
    'cred.6': 'the araucarias, the half-timbered houses',
    'cred.7': 'and the stories told by the wood stove.',
    'cred.8': 'Thanks for playing!',

    /* ================= CHAPTER 2 — THE RIBBON TRAIL ================= */
    'menu.chapters': 'CHAPTERS',
    'chap.title': 'CHOOSE A CHAPTER',
    'chap.1': '1 — THE SLEEPING TOWN',
    'chap.2': '2 — THE RIBBON TRAIL',
    'chap.1.d': 'Arno returns to Teewald after twenty years and wakes up in an empty town overrun by creatures.',
    'chap.2.d': 'Dona Frida tells the legend of the Old One. Arno goes hunting the demon, following the blessed ribbons.',
    'stage2.num': 'STAGE 2',
    'stage2.name': 'THE RIBBON TRAIL',
    'mission': 'MISSION',
    'mission.2': 'Find Long-Hands before the moon goes down. Follow the seven blessed ribbons.',
    'hint.gun': 'V  or  ↑ + X  =  FIRE THE .38',
    'hint.gun@touch': '↑ + B  =  FIRE THE .38',
    'hint.boss2': 'JUMP THE CHARGE!  LEAVE THE LEAP\'S SHADOW!',
    'gun.empty': 'OUT OF AMMO!',
    'gun.bullets': 'ROUNDS',
    'item.balas': 'BOX OF .38 ROUNDS',
    'item.revolver': '.38 REVOLVER',
    'ctrl.shoot': 'REVOLVER (CH. 2)',
    'ctrl.keys7': 'V / ↑ + X',
    'ctrl.keys7@touch': '↑ + B',
    'en.colono': 'POSSESSED',
    'en.colona': 'POSSESSED',
    'en.kessler': 'OLD KESSLER',
    'en.wolf': 'WEREWOLF',
    'en.sack': 'POTATO SACK',
    'boss2.name': 'THE ANCIENT DEMON',
    'freed.m': 'FREED!',
    'freed.f': 'FREED!',
    'name.kessler': 'MR. KESSLER',
    'name.fita': 'BLESSED RIBBON',
    'name.demon': 'DER ALTE',

    'ch2.card1': 'Teewald City — the same night',
    'ch2.card2': 'The parish church — the night that never ends',
    'p2.1': 'Have some chimarrão, boy. Warms the soul. Nobody lights a fire out there anymore.',
    'p2.2': 'Bah... twenty years without a proper mate. Bitter as anything, Dona Frida.',
    'p2.3': 'What\'s bitter is what\'s walking out there. Listen close, I\'ll only tell this once.',
    'p2.l1': 'In 1852 our grandparents crossed the ocean on a sailing ship. They came from the Hunsrück, in the Rhineland, with a Bible, a hoe and a sack of seed potatoes.',
    'p2.l2': 'But someone else rode in the hold. Back in Germany they called it der Alte, the Old One: a thing that crawls on all fours down forest roads on foggy nights and takes whoever walks alone.',
    'p2.l3': 'Up here in the highlands it found everything it wanted: thick woods, fog and lonely people. Until my great-grandmother Hedwig, Teewald\'s first healer, bound it to the roots of the Old Pine.',
    'p2.l4': 'The oldest araucaria in Teewald. Seven blessed ribbons and a prayer. The mate pickers, who had seen the thing among the yerba, gave it another name: Long-Hands.',
    'p2.l5': 'To keep the binding tight, every May the girls danced the pau-de-fita, the ribbon dance, around the Old Pine. Every turn braided the ribbons. Every ribbon, a knot.',
    'p2.l6': 'Over the years nobody remembered why. It became a festival, with a brass band, beer and a queen. Only the healers kept the secret.',
    'p2.l7': 'This year old Kessler from the sawmill felled the Old Pine for the planks of the new Potato Festival hall. Hardwood. Worth a fortune.',
    'p2.l8': 'They danced the pau-de-fita around a eucalyptus pole in the square. It bound nothing.',
    'p2.l9': 'That very night the fog rolled in. The Old One crawled out of the stump, the ribbons still tangled in its hide. And the night never ended.',
    'p2.4': 'And the prayer? Do you know your great-grandmother\'s prayer?',
    'p2.5': 'Oma Hedwig took the prayer to her grave. But she embroidered each verse on one of the ribbons, in cross-stitch, so she wouldn\'t forget.',
    'p2.6': 'The thing is wounded, roaming Teewald, shedding ribbons as it goes. Follow the ribbons, Arno. They\'ll lead you to it, and give you the whole prayer.',
    'p2.7': 'Hunting a demon with a rosary and a gourd of mate... My father would laugh in my face.',
    'p2.8': 'Not just with that. I found this at the bend on the mountain road, thrown in the bushes. It was in your truck\'s glovebox.',
    'p2.9': 'My .38! ...And the truck, Dona Frida?',
    'p2.10': 'Not a trace of the truck. I blessed the revolver: a bullet from a blessed gun hits what ordinary bullets can\'t. The Shooting Club should still have ammunition.',
    'p2.11': 'It goes back to the Old Pine\'s stump before the moon goes down. That\'s where you end this. Go with God, boy.',
    'p2.12': 'Keep the kettle on, Dona Frida. I\'ll be back for a second round.',

    'b2.pavilion': 'The new festival hall... Still smells of resin. That\'s the Old Pine, cut into planks.',
    'b2.mill': 'The Webers\' old mill. The wheel still turns... by itself. Nobody left to grind the corn.',
    'b2.sawmill': 'Kessler\'s sawmill. Dad used to unload logs here, and I\'d play in the sawdust piles.',
    'b2.fnm': 'An FNM loaded with pine... Just like Dad\'s. He called his the Old Red.',
    'b2.ervateira': 'The Becker yerba grove. It was my grandfather\'s. Someone lit the carijó... Smell that toasted yerba?',
    'b2.clearing': 'Way back, in the middle of the clearing... the Old Pine\'s stump. The ribbons are trembling in my pocket.',
    'tz.1': 'There, on the log pile! Long-Hands...!',
    'tz.2': 'Run all you want. Your ribbons are all ending up with me.',

    'rib.count': 'RIBBON %n OF 7, hand-embroidered:',
    'rib.v0': 'Old pine, your roots run deep,',
    'rib.v1': 'hold the hellish thing asleep.',
    'rib.v2': 'In the fog you crept,',
    'rib.v3': 'by the blessed ribbon you\'re kept.',
    'rib.v4': 'Seven ribbons, seven knots:',
    'rib.v5': 'back in the earth is where you rot.',
    'rib.v6': 'Im Namen Gottes. Amen.',
    'rib.first': 'Cross-stitch, like my grandmother\'s tablecloths. It\'s a verse of the prayer!',
    'rib.mid': 'Half the prayer. I can feel the thing close... the ribbon is warm in my hand.',
    'rib.last': 'German... Grandma prayed like that. Seven ribbons, the whole prayer. Now we\'re talking, Long-Hands.',

    'k.1': 'Gott im Himmel... The saw... I couldn\'t stop the saw...',
    'k.2': 'Mr. Kessler? It\'s me, Arno. The Becker boy, from the log truck.',
    'k.3': 'The Becker boy... It was me, Arno. I felled the Old Pine. They paid good money for the wood, and the new hall was going to be so beautiful...',
    'k.4': 'That same night it crawled out of the stump, with the ribbon-dance ribbons tangled in its hide. And it put me to sawing planks nonstop, day and night. Only there are no days anymore.',
    'k.5': 'Listen: it charges on all fours like a mad bull. Jump over it and hit it when it rams its head into a trunk. And when it crouches, get out from under, because it\'s going to leap!',
    'k.6': 'Here. This fell off its hide when it came through. Got caught in the sawdust.',
    'k.7': 'Go to the church, Mr. Kessler. Dona Frida is there, with hot mate.',
    'k.8': 'Arno... your father. In \'77, on a foggy night, his truck turned up parked at the gate of the yerba grove. Empty. Engine running.',
    'k.9': '...They said he went off the cliff.',
    'k.10': 'They said.',

    'boss2.a1': 'The Old Pine\'s stump... It has to come back here. I\'ll wait.',
    'boss2.d1': 'Becker... Der Bub vom Becker.',
    'boss2.d2': 'You smell like your father, boy. He came alone too, one foggy night.',
    'boss2.a2': '...What do you know about my father?!',
    'boss2.a3': 'Enough talk, Long-Hands. Tonight you go back in your hole.',
    'bind.1': 'Oma Hedwig, lend me your prayer...',
    'bind.2': 'There, Dona Frida. Bound again. Now we just wait for the sun.',

    'e2.1': 'It\'s over. The thing turned to ash and went into the stump.',
    'e2.2': '...But where\'s the dawn? The moon hasn\'t moved an inch.',
    'e2.3': 'Music...? A brass band. It\'s coming from below... from inside the stump!',
    'e2.4': 'Prost! Cheers! Another round for the Weber table!',
    'e2.5': 'Play the waltz, Erwin! The Potato Queen hasn\'t danced yet!',
    'e2.6': 'Arno! Hey, Arno! Come on down, boy! The band is playing our waltz!',
    'e2.7': '...Dad?',
    'end2.chapter': 'END OF CHAPTER 2',
    'end2.next': 'Chapter 3: The Dance Beneath the Earth',
    'cred2.2': 'Chapter 2 — The Ribbon Trail',
    'cred2.3': 'Legends, customs and places',
    'cred2.4': 'the ribbon dance, the folk healer, the carijó,',
    'cred2.5': 'the colonial mill, the sawmill and the FNM,',
    'cred2.6': 'chimarrão and the Potato Festival.',

    'sign2.brewery': 'SCHMITT BREWERY — SINCE 1923\nColonial draft beer, light and dark.\n"Ein Prosit!" Closed until further notice.',
    'sign2.tiro': 'TEEWALD SHOOTING CLUB — 1898\nShooting King 1997: Helmut Weber.\nAmmunition kept in the storeroom.',
    'sign2.rainha': 'POTATO QUEEN 1997: Ingrid Weber.\nPrincesses: Elke Schmitt and Rosi Kessler.\nDance with Erwin\'s Little Band.',
    'sign2.missing2': 'HAS ANYONE SEEN THE KESSLER FAMILY?\nThe sawmill never stops running,\nbut nobody goes in or out.',
    'sign2.pavilion': 'POTATO FESTIVAL HALL\nBuilt by Kessler Sawmill.\nHardwood: 100% pine.',
    'sign2.mill': 'WEBER FAMILY MILL\nCornmeal, corn flour and manioc flour.\nGround by the creek\'s water.',
    'sign2.sawmill': 'KESSLER SAWMILL\nBuying standing pine trees.\nCash on the spot.',
    'sign2.ervateira': 'BECKER YERBA GROVE — SINCE 1889\nYerba flame-dried in the carijó\nand ground the old way.',
    'sign2.stump': 'An old board, carved with a pocketknife:\n"HIER WIRD NICHT GEHAUEN — 1852"\n(Here nothing is cut.)',

    /* ================= CHAPTER 3 — THE DANCE BENEATH THE EARTH ================= */
    'chap.3': '3 — THE DANCE BENEATH THE EARTH',
    'chap.3.d': 'Arno goes down the stairs inside the stump to the hall where Teewald\'s missing still dance. His father is down there.',
    'stage3.num': 'STAGE 3',
    'stage3.name': 'THE DANCE BENEATH THE EARTH',
    'mission3.2': 'Go down to the ballroom and bring your father back up.',
    'hint.boss3': 'JUMP THE LASSO, THE BOLAS AND THE SPIN!',
    'm.fast': 'Play it faster, Erwin!',
    'm.dodge': 'Too slow!',
    'en.miner': 'MINER',
    'en.bat': 'BAT',
    'en.dancer': 'DANCERS',
    'en.cart': 'MINE CART',
    'boss3.name': 'THE STRANGER AT THE DANCE',
    'freed.p': 'FREED!',
    'name.ewald': 'EWALD BECKER',
    'name.moco': 'THE STRANGER',
    'name.ingrid': 'INGRID WEBER',
    'ch3.card1': 'Beneath the Old Pine\'s stump',
    'ch3.card2': 'A stairway that was on no map',
    'p3.1': 'Stone stairs, inside a tree stump... This is older than the town.',
    'p3.2': 'Prost! Cheers! Another round for the Weber table!',
    'p3.3': 'Names scratched into the steps with a pocketknife. Schmitt, 1898... Weber, 1931... Kessler, 1997...',
    'p3.4': '...Becker, 1977.',
    'p3.5': 'Hold on, Dad. I\'m coming down.',
    'b3.lamp': 'A carbide lamp hanging at the bottom of the stairs... Still lights. Bah, better than nothing.',
    'b3.roots': 'The Old Pine\'s roots. They go down farther than I can see.',
    'b3.mine': 'A coal mine under Teewald? Grandpa talked about a mine that caved in back in \'31, with twelve men inside. Nobody believed him.',
    'b3.barbara': 'Saint Barbara, patron of miners. Someone still lights candles for her down here.',
    'b3.lift': 'The mine\'s cargo lift. If I go down, there\'s no way back... Bah, I\'ve come this far.',
    'b3.cave': 'A cave... And somewhere down there, the waltz. Louder and louder.',
    'b3.ballroom': 'Mother of God... It\'s the Festival. Everyone who went missing, dancing under the earth.',
    'b3.stage': 'In the middle of the floor... a young man in a black hat, dancing with the Potato Queen.',
    'fa.1': 'Dad...? DAD!',
    'fa.2': '...one, two, three... one, two, three... Lovely waltz, Erwin. Play it again.',
    'fa.3': 'Dad, it\'s me! Arno! Look at me!',
    'fa.4': 'Whoever doesn\'t dance doesn\'t stay at the dance.',
    'fa.5': 'Then I\'ll dance my own way.',
    'm.1': 'Good evening, Becker. Right on time for the waltz.',
    'm.2': 'Who are you?',
    'm.3': 'Back in the Hunsrück they called me Tanzteufel, the dance devil. Up in these hills they call me the Stranger at the Dance. Every party gets a handsome young man nobody invited.',
    'm.4': 'Your father danced with me in \'77. Light on his feet, that Ewald. And you came alone, just like him.',
    'm.4b': 'Did you like the voice up there? "Come on down, boy!" I can sound like anyone who ever danced with me.',
    'm.5': 'Let my father go. Let everyone go.',
    'm.6': 'Nobody leaves the floor before the last song. And the last song is mine to play.',
    'm.8': 'No one... ever... looked at my feet...',
    'm.9': 'Goat hooves. Grandma always said: at a dance, before you take a handsome stranger\'s hand, look at his feet.',
    'e3.1': 'Where are we? The Festival... we were dancing in the hall...',
    'e3.2': 'Arno? ...But you\'re a grown man. With a mustache, just like your grandpa.',
    'e3.3': 'Dad... It\'s been twenty years.',
    'e3.4': 'Twenty years? I only came down to fetch Erwin, who\'d gone missing at the yerba plant. Five minutes, it was supposed to be. I even left the truck running.',
    'e3.5': 'My watch stopped... Eleven forty-seven.',
    'e3.6': 'That\'s when I lost the truck on the mountain road.',
    'e3.7': 'Then it was him who called you here. Forgive me, boy.',
    'e3.8': 'Let\'s go home, Dad. Dona Frida left the kettle on.',
    'e3.9': 'I told you I\'d keep the kettle on.',
    'e3.10': 'Frida? Bah, you got old!',
    'e3.11': 'And you\'re twenty years late, Ewald Becker. Have some mate.',
    'e3.12': 'Look, Dad. The sun.',
    'e3.cap': 'The first morning in Teewald since the Potato Festival.',
    'e3.r1': '...ksshh... 104.5, the mountain station... the dance is over... ksshh... but the fog... ksshh... hasn\'t all lifted yet...',
    'end3.chapter': 'END OF CHAPTER 3',
    'cred3.2': 'Chapter 3 — The Dance Beneath the Earth',
    'cred3.3': 'Legends, customs and places',
    'cred3.4': 'the stranger at the dance and his goat hooves,',
    'cred3.5': 'the coal mine and Saint Barbara,',
    'cred3.6': 'the brass band, the kerb and Dad\'s waltz.',
    'sign3.board': 'A board nailed to the wall:\n"WHOEVER GOES DOWN TO THE DANCE\nDOESN\'T COME UP BEFORE THE LAST SONG."',
    'sign3.mine': 'SAINT BARBARA MINE\nTeewald Coal Company — 1904.\nClosed after the 1931 cave-in.',
    'sign3.grisu': 'DANGER: FIREDAMP\nNo matches or lamps\nwithout the foreman\'s orders.',
    'sign3.barbara': 'Saint Barbara, protector of miners,\ndeliver us from lightning, fire and cave-ins.\n(Twelve names scratched below.)',
    'sign3.lift': 'CARGO LIFT\nCapacity: 2 mine carts or 8 men.\nDo not jump while it is moving.',
    'sign3.river': 'Chalked on the rock:\n"THE DARK RIVER HAS NO BOTTOM."\n— the miners of \'31',
    'sign3.ballroom': 'KERB DANCE — FREE ENTRY\nDress: your Sunday best.\nErwin\'s Little Band, playing since 1852.',
    'sign3.queen': 'QUEENS OF THE DANCE: Lotte Schmitt (1898),\nHilda Weber (1931), Irmgard Kessler (1977)\nand Ingrid Weber (1997).'
  };

  TC.LANG = L;
  TC.t = function (key) {
    var lang = TC.opts.lang || 'pt';
    var s;
    if (TC.input && TC.input.touchUI && TC.input.touchUI()) {
      s = L[lang][key + '@touch'];
      if (s == null) s = L.pt[key + '@touch'];
      if (s != null) return s;
    } else if (TC.input && TC.input.device && TC.input.device() === 'pad') {
      // jogando com controle: {jump} vira o nome do botão (A, ✕, B, [3]...); {attack*} lista todos
      s = L[lang][key + '@pad'];
      if (s == null) s = L.pt[key + '@pad'];
      if (s != null) return s.replace(/\{(\w+)(\*?)\}/g, function (m, a, all) { return TC.input.padLabel(a, !!all); });
    }
    s = L[lang][key];
    if (s == null) s = L.pt[key];
    return s == null ? key : s;
  };
})();
