'use strict';
/* Teewald City — textos do capítulo 4 ("O Último Turno") e nomes de personagens usados nos capítulos 4 a 7 */
(function () {
  var L = TC.LANG;

  /* nomes compartilhados (caixas de diálogo) */
  Object.assign(L.pt, {
    'name.rosa': 'DONA ROSA',
    'name.gerhard': 'SEU GERHARD',
    'name.hilde': 'HILDE',
    'name.kid': 'CRIANÇA',
    'name.lena': 'LENA',
    'name.hedwig': 'OMA HEDWIG',
    'name.jacob': 'JACOB BECKER',
    'name.vogt': 'JOHANN VOGT',
    'name.pelz': 'O PELZNICKEL',
    'name.arnoldo': 'SEU ARNOLDO',
    'name.helmut': 'SEU HELMUT',
    'name.alte': 'O ANTIGO',
    'name.boitata': 'A BOITATÁ'
  });
  Object.assign(L.en, {
    'name.rosa': 'DONA ROSA',
    'name.gerhard': 'MR. GERHARD',
    'name.hilde': 'HILDE',
    'name.kid': 'CHILD',
    'name.lena': 'LENA',
    'name.hedwig': 'OMA HEDWIG',
    'name.jacob': 'JACOB BECKER',
    'name.vogt': 'JOHANN VOGT',
    'name.pelz': 'THE PELZNICKEL',
    'name.arnoldo': 'MR. ARNOLDO',
    'name.helmut': 'MR. HELMUT',
    'name.alte': 'THE OLD ONE',
    'name.boitata': 'THE BOITATÁ'
  });

  /* ================= CAPÍTULO 4 — O ÚLTIMO TURNO ================= */
  Object.assign(L.pt, {
    'chap.4': '4 — O ÚLTIMO TURNO',
    'chap.4.d': 'O apito da fábrica de calçados toca à meia-noite e as mulheres de Teewald saem de casa dormindo.',
    'stage4.num': 'FASE 4',
    'stage4.name': 'O ÚLTIMO TURNO',
    'mission4': 'Siga as sonâmbulas até a Calçados Morgenstern e descubra quem está tocando o apito da fábrica.',
    'c4.card1': 'Teewald City — a noite seguinte',
    'c4.card2': 'A curva da serra',
    // prólogo: a curva da serra
    'c4.p1': 'Ali, pai. O meu caminhão. Igualzinho a ontem, de farol aceso.',
    'c4.p2': 'E com o motor ligado. Igual o meu em 77, na porteira da ervateira.',
    'c4.p3': 'Ei! EI! Volta aqui!',
    'c4.p4': 'Desceu a serra sozinho... pro lado da baixada do arroio.',
    'c4.p5': 'O apito da Morgenstern... A fábrica fechou em março. Quem é que tá apitando?',
    'c4.p6': 'Olha, pai. As mulheres da vila... de camisola e de olho fechado.',
    'c4.p7': 'Ingrid? Ingrid! ...Não escuta. Anda feito sonâmbula.',
    'c4.p8': 'Eu carregava sapato dessa fábrica toda quinta. Tu ia junto, lembra? A moça do pesponto te dava bala de goma.',
    'c4.p9': 'A Hilde... Ela morreu no incêndio de 67.',
    'c4.p10': 'E na manhã seguinte eu levei a carga pro porto. Sapato com cheiro de fumaça. Nunca perguntei nada.',
    'c4.p11': 'Vai pra igreja, pai. Fica com a Dona Frida. Eu vou atrás delas.',
    // falas na fase
    'c4.b.vila': 'A vila operária. Todas as portas abertas e nenhuma luz acesa.',
    'c4.b.sleep': 'Elas não acordam. Andam de olho fechado, direto pro portão da fábrica.',
    'c4.b.gate': 'Calçados Morgenstern. "Do Rio Grande para o mundo." O neon ainda pisca.',
    'c4.b.curtume': 'O curtume. Esse cheiro de couro e tanino... o pai dizia que dava pra sentir da estrada.',
    'c4.b.truck': 'O meu caminhão! Lá na doca de carga, de farol aceso... e ninguém na cabine.',
    'c4.b.fulao': 'O fulão ainda gira. E tem alguma coisa se mexendo dentro do tanque.',
    'c4.b.inside': 'As esteiras andando sozinhas. Fôrma, sola, cola... trinta anos sem ninguém.',
    'c4.b.press': 'Cuidado com o balancim. Essa prensa corta couro como se fosse papel.',
    'c4.b.pesponto': 'O pesponto. Sessenta máquinas... e as mulheres de Teewald costurando de olho fechado.',
    'c4.b.cola': 'A sala de cola. Esse cheiro arde até os olhos. Foi aqui que começou o fogo.',
    'c4.b.boss': 'Lá no fundo. Uma moça de avental... flutuando no meio das máquinas.',
    'c4.punch': 'PONTO BATIDO',
    // o escritório do velho Gerhard
    'c4.g1': 'Tu é o guri do Becker. O caminhoneiro das quintas.',
    'c4.g2': 'Seu Gerhard Morgenstern? O senhor ainda mora aqui?',
    'c4.g3': 'Ela não me deixa ir embora. Toda noite as máquinas ligam sozinhas e o apito toca. Trinta anos.',
    'c4.g4': 'A Hilde.',
    'c4.g5': 'Eu tranquei a porta do pesponto. Pra ninguém roubar sapato. Três serões seguidos pra fechar o pedido dos americanos.',
    'c4.g6': 'Na terceira madrugada a cola pegou fogo. A chave tava no meu bolso.',
    'c4.g7': 'Carrego ela no pescoço desde 1967. Abre aquelas portas, guri. Eu nunca tive coragem.',
    'c4.g8': 'E esses sapatos vermelhos na vitrine?',
    'c4.g9': 'O primeiro par do Modelo Hilde. Ela costurou com retalho, pro baile de Kerb. Eu botei o nome dela no sapato e vendi cem mil pares.',
    'c4.g10': 'Esses aqui não são seus, Seu Gerhard.',
    'item.chave': 'CHAVE DO PESPONTO',
    'item.sapatos': 'SAPATOS VERMELHOS',
    // a Moça do Serão
    'boss4.name': 'A MOÇA DO SERÃO',
    'c4.h1': '...mais um par... mais um par... o caminhão do Becker vem buscar na quinta...',
    'c4.h2': 'Hilde? Sou eu, o guri do Becker. O das balas de goma.',
    'c4.h3': 'Ninguém sai antes de fechar o pedido. Dez mil pares. A porta só abre de manhã.',
    'c4.h4': 'Senão a fábrica fecha. Senão ninguém come. As moças precisam terminar.',
    'c4.h5': 'A fábrica já fechou, Hilde. Faz trinta anos que tu tá trancada aqui.',
    'c4.h6': 'Então tu fica também. Senta. Tem máquina sobrando.',
    'c4.fire': 'O FOGO! A PORTA! ABRAM A PORTA!',
    'c4.door': 'PORTA ABERTA!',
    'c4.doorhint': '↑ ABRIR',
    'c4.shield': 'O FOGO VOLTOU!',
    'c4.stitched': 'COSTURADO!',
    'hint.boss4': 'PULE A COSTURA!  DEVOLVA A FÔRMA COM UM SOCO!',
    'hint.doors': 'ABRA AS TRÊS PORTAS COM A CHAVE:  ↑',
    'hint.glue': 'A COLA DEIXA O ARNO LENTO!',
    // o fim da Hilde
    'c4.e1': 'Tava trancada... Eu batia na porta e ninguém abria.',
    'c4.e2': 'Agora tá aberta, Hilde. Todas elas.',
    'c4.e3': 'E isso aqui é teu. O Seu Gerhard guardou trinta anos.',
    'c4.e4': 'O meu sapato vermelho... Eu costurei pro baile de Kerb. Nunca cheguei a dançar.',
    'c4.e5': 'Com sapato nos pés, a gente pode ir embora.',
    'c4.e6': 'Obrigada, guri. Tu ainda gosta de bala de goma?',
    // inimigos
    'en.shoes': 'MODELO HILDE',
    'en.clog': 'TAMANCOS',
    'en.boot': 'BOTINA DE BICO DE AÇO',
    'en.foreman': 'CONTRAMESTRE',
    'en.couro': 'O COURO',
    'c4.meta': 'A META!',
    'c4.wrap': 'SACUDA!',
    // placas
    'sign4.vila': 'VILA OPERÁRIA MORGENSTERN\nCasas para os funcionários.\nAluguel descontado na folha.',
    'sign4.gate': 'CALÇADOS MORGENSTERN S.A. — 1949\nDo Rio Grande para o mundo.\nPrecisa-se de pespontadeiras.',
    'sign4.closed': 'COMUNICADO: a empresa encerra suas\natividades em 31/03/1997. A direção\nagradece os 48 anos de trabalho.',
    'sign4.curtume': 'CURTUME MORGENSTERN\nCouro curtido a tanino de acácia-negra.\nProibido fumar perto do fulão.',
    'sign4.ponto': 'RELÓGIO DE PONTO\nQuem não bate o ponto\nnão recebe o dia.',
    'sign4.acidentes': 'ESTAMOS HÁ 10.963 DIAS\nSEM ACIDENTES DE TRABALHO.\n(A contagem começou em 1967.)',
    'sign4.meta': 'META DO DIA: 2.400 PARES.\nQuem não bate a meta faz serão.',
    'sign4.cola': 'SALA DE COLA\nInflamável! Não acender fósforo.\nPorta trancada após as 22h.',
    'sign4.poster': 'MODELO HILDE — 1967\n"O sapato que conquistou a América."\nExportação para os Estados Unidos.',
    'sign4.clock': 'O relógio da parede parou\nnas 3h15 da madrugada.',
    // final do capítulo
    'c4.f1': 'Que lugar é esse? Eu tava dormindo em casa...',
    'c4.f2': 'Tá tudo bem, Ingrid. Acabou o serão. Vamos pra casa.',
    'c4.f3': 'O meu caminhão!',
    'c4.f4': 'O meu caminhão... tá comendo a luz.',
    'c4.f5': 'Arno! Tu tá inteiro, guri?',
    'c4.f6': 'O caminhão, pai. Subiu por aquela estrada.',
    'c4.f7': 'Aquela estrada sobe pro Morro dos Bugres. Ninguém sobe lá.',
    'c4.f8': 'Amanhã cedo a gente vai falar com a Dona Rosa. Ela conhece aquele morro melhor que ninguém.',
    'c4.r1': '...ksshh... 104,5... mais vacas amanhecem sem os olhos na Linha Becker... ksshh... o povo já fala em chupa-cabra...',
    'end4.chapter': 'FIM DO CAPÍTULO 4',
    'cred4.2': 'Capítulo 4 — O Último Turno',
    'cred4.3': 'Lendas, costumes e lugares',
    'cred4.4': 'a fábrica de calçados e o curtume,',
    'cred4.5': 'o pesponto, o serão e o apito,',
    'cred4.6': 'e as pespontadeiras de 1967.'
  });

  Object.assign(L.en, {
    'chap.4': '4 — THE LAST SHIFT',
    'chap.4.d': 'The shoe factory whistle blows at midnight and the women of Teewald walk out of their homes asleep.',
    'stage4.num': 'STAGE 4',
    'stage4.name': 'THE LAST SHIFT',
    'mission4': 'Follow the sleepwalkers to the Morgenstern shoe factory and find out who is blowing the factory whistle.',
    'c4.card1': 'Teewald City — the next night',
    'c4.card2': 'The bend on the mountain road',
    'c4.p1': 'There, Dad. My truck. Just like last night, headlights on.',
    'c4.p2': 'And the engine running. Same as mine in \'77, at the gate of the yerba grove.',
    'c4.p3': 'Hey! HEY! Come back!',
    'c4.p4': 'It rolled down the hill on its own... toward the creek bottoms.',
    'c4.p5': 'The Morgenstern whistle... The factory shut down in March. Who\'s blowing it?',
    'c4.p6': 'Look, Dad. The women from the workers\' row... in nightgowns, eyes closed.',
    'c4.p7': 'Ingrid? Ingrid! ...She can\'t hear me. She\'s sleepwalking.',
    'c4.p8': 'I hauled shoes from that factory every Thursday. You came along, remember? The stitching girl gave you gumdrops.',
    'c4.p9': 'Hilde... She died in the fire of \'67.',
    'c4.p10': 'And the next morning I took the load to the port. Shoes that smelled of smoke. I never asked a thing.',
    'c4.p11': 'Go to the church, Dad. Stay with Dona Frida. I\'m going after them.',
    'c4.b.vila': 'The workers\' row. Every door open and not a single light on.',
    'c4.b.sleep': 'They won\'t wake up. Eyes closed, walking straight to the factory gate.',
    'c4.b.gate': 'Morgenstern Shoes. "From Rio Grande to the world." The neon still flickers.',
    'c4.b.curtume': 'The tannery. That smell of leather and tannin... Dad said you could smell it from the highway.',
    'c4.b.truck': 'My truck! Over at the loading dock, headlights on... and nobody in the cab.',
    'c4.b.fulao': 'The tanning drum is still turning. And something is moving in the vat.',
    'c4.b.inside': 'The belts running by themselves. Last, sole, glue... thirty years with nobody here.',
    'c4.b.press': 'Watch out for the clicker press. It cuts leather like paper.',
    'c4.b.pesponto': 'The stitching floor. Sixty machines... and the women of Teewald sewing with their eyes closed.',
    'c4.b.cola': 'The glue room. The fumes sting your eyes. This is where the fire started.',
    'c4.b.boss': 'Way in the back. A girl in an apron... floating among the machines.',
    'c4.punch': 'CLOCKED IN',
    'c4.g1': 'You\'re the Becker boy. The Thursday trucker\'s son.',
    'c4.g2': 'Mr. Gerhard Morgenstern? You still live here?',
    'c4.g3': 'She won\'t let me leave. Every night the machines start on their own and the whistle blows. Thirty years.',
    'c4.g4': 'Hilde.',
    'c4.g5': 'I locked the stitching room. So nobody would steal shoes. Three night shifts in a row to fill the American order.',
    'c4.g6': 'On the third night the glue caught fire. The key was in my pocket.',
    'c4.g7': 'I\'ve worn it round my neck since 1967. Open those doors, boy. I never had the courage.',
    'c4.g8': 'And those red shoes in the display case?',
    'c4.g9': 'The first pair of the Hilde Model. She sewed them from scraps, for the Kerb dance. I put her name on the shoe and sold a hundred thousand pairs.',
    'c4.g10': 'These aren\'t yours, Mr. Gerhard.',
    'item.chave': 'STITCHING ROOM KEY',
    'item.sapatos': 'RED SHOES',
    'boss4.name': 'THE NIGHT-SHIFT GIRL',
    'c4.h1': '...one more pair... one more pair... the Becker truck comes for the load on Thursday...',
    'c4.h2': 'Hilde? It\'s me, the Becker boy. The gumdrop kid.',
    'c4.h3': 'Nobody leaves before the order is done. Ten thousand pairs. The door opens in the morning.',
    'c4.h4': 'Or the factory closes. Or nobody eats. The girls have to finish.',
    'c4.h5': 'The factory already closed, Hilde. You\'ve been locked in here for thirty years.',
    'c4.h6': 'Then you stay too. Sit down. There\'s a spare machine.',
    'c4.fire': 'THE FIRE! THE DOOR! OPEN THE DOOR!',
    'c4.door': 'DOOR OPEN!',
    'c4.doorhint': '↑ OPEN',
    'c4.shield': 'THE FIRE IS BACK!',
    'c4.stitched': 'STITCHED!',
    'hint.boss4': 'JUMP THE SEAM!  PUNCH THE SHOE LAST BACK!',
    'hint.doors': 'OPEN THE THREE DOORS WITH THE KEY:  ↑',
    'hint.glue': 'THE GLUE SLOWS ARNO DOWN!',
    'c4.e1': 'I was locked in... I pounded on the door and nobody opened it.',
    'c4.e2': 'It\'s open now, Hilde. All of them.',
    'c4.e3': 'And this is yours. Mr. Gerhard kept it for thirty years.',
    'c4.e4': 'My red shoes... I sewed them for the Kerb dance. I never got to dance.',
    'c4.e5': 'With shoes on your feet, you can finally leave.',
    'c4.e6': 'Thank you, boy. Do you still like gumdrops?',
    'en.shoes': 'HILDE MODEL',
    'en.clog': 'WOODEN CLOGS',
    'en.boot': 'STEEL-TOE BOOT',
    'en.foreman': 'FOREMAN',
    'en.couro': 'THE HIDE',
    'c4.meta': 'THE QUOTA!',
    'c4.wrap': 'SHAKE!',
    'sign4.vila': 'MORGENSTERN WORKERS\' ROW\nHousing for employees.\nRent deducted from wages.',
    'sign4.gate': 'MORGENSTERN SHOES INC. — 1949\nFrom Rio Grande to the world.\nStitchers wanted.',
    'sign4.closed': 'NOTICE: the company ceases\noperations on 03/31/1997. Management\nthanks you for 48 years of work.',
    'sign4.curtume': 'MORGENSTERN TANNERY\nLeather tanned with black wattle bark.\nNo smoking near the drum.',
    'sign4.ponto': 'TIME CLOCK\nNo punch,\nno pay.',
    'sign4.acidentes': 'WE HAVE GONE 10,963 DAYS\nWITHOUT A WORKPLACE ACCIDENT.\n(The count began in 1967.)',
    'sign4.meta': 'DAILY QUOTA: 2,400 PAIRS.\nMiss the quota, work the night shift.',
    'sign4.cola': 'GLUE ROOM\nFlammable! No matches.\nDoor locked after 10 PM.',
    'sign4.poster': 'HILDE MODEL — 1967\n"The shoe that conquered America."\nExported to the United States.',
    'sign4.clock': 'The wall clock stopped\nat 3:15 in the morning.',
    'c4.f1': 'Where am I? I was asleep at home...',
    'c4.f2': 'It\'s all right, Ingrid. The night shift is over. Let\'s go home.',
    'c4.f3': 'My truck!',
    'c4.f4': 'My truck... it\'s eating the light.',
    'c4.f5': 'Arno! Are you in one piece, boy?',
    'c4.f6': 'The truck, Dad. It went up that road.',
    'c4.f7': 'That road climbs to the Morro dos Bugres. Nobody goes up there.',
    'c4.f8': 'First thing tomorrow we go talk to Dona Rosa. She knows that hill better than anyone.',
    'c4.r1': '...ksshh... 104.5... more cows found with their eyes gone on the Becker road... ksshh... folks are already saying chupacabra...',
    'end4.chapter': 'END OF CHAPTER 4',
    'cred4.2': 'Chapter 4 — The Last Shift',
    'cred4.3': 'Legends, customs and places',
    'cred4.4': 'the shoe factory and the tannery,',
    'cred4.5': 'the stitching floor, the night shift and the whistle,',
    'cred4.6': 'and the stitchers of 1967.'
  });
})();
