'use strict';
/* Teewald City — textos do capítulo 5 ("A Noite Grande" / "The Great Night") */
(function () {
  var L = TC.LANG;

  Object.assign(L.pt, {
    'chap.5': '5 — A NOITE GRANDE',
    'chap.5.d': 'Os faróis sobem o Morro dos Bugres. Lá em cima, alguém está comendo a luz.',
    'stage5.num': 'FASE 5',
    'stage5.name': 'A NOITE GRANDE',
    'mission5': 'Suba o morro até a caverna e traga o teu caminhão de volta. Se os olhos abrirem, feche os teus.',

    'hint.c5cover': 'SEGURE ↓: FECHE OS OLHOS!',
    'hint.c5cover@touch': 'SEGURE ↓ NO DIRECIONAL: FECHE OS OLHOS!',
    'hint.c5stuck': 'A CABEÇA CRAVOU NO CHÃO: BATA AGORA!',
    'hint.c5spit': 'DERRUBE OS OLHOS A SOCO OU A BALA!',
    'hint.c5bite': 'A CABEÇA FICOU PRESA NA TÁBUA: SOQUE!',
    'hint.c5cones': 'SAIA DE BAIXO DAS SOMBRAS!',
    'hint.c5beam': 'LUZ ALTA! ELA ENGOLE O FAROL E FICA TONTA!',
    'hint.c5pinha': 'PINHAS CAINDO: SAIA DE BAIXO DA SOMBRA!',
    'hint.c5jacob': 'SAIA DA MIRA!  PULE A BATIDA!  FUJA DO FOGO!',
    'hint.c5boss1': 'ESPERE O BOTE: QUANDO ELA CRAVAR A CABEÇA, BATA!',
    'hint.c5road': 'BATA NA CABEÇA QUANDO ELA MORDER OU FICAR TONTA!',
    'c5.oxcalm': 'SOSSEGOU',
    'c5.whistle': '(assobio)',
    'c5.hard': 'DE RASPÃO!',
    'c5.hard2': 'DE RASPÃO!',
    'c5.eyes': 'OS OLHOS!',
    'c5.dazzled': 'OFUSCADO...',
    'c5.dazzle': 'OFUSCADO!',
    'c5.safe': 'UFA...',
    'c5.curve': 'CURVA!',
    'c5.curve2': 'SEGURA, GURI!',
    'c5.beam': 'LUZ ALTA!',
    'c5.firecp': 'FOGO ACESO',
    'item.pinhao': 'PINHÃO COZIDO',
    'en.c5ox': 'BOI SEM OLHO',
    'en.c5dog': 'CÃO DO BUGREIRO',
    'en.c5erv': 'ERVATEIRO',
    'en.c5eye': 'OLHO VOADOR',
    'en.c5orb': 'OLHO',
    'en.c5bale': 'FARDO DE FENO',
    'en.c5raido': 'SACO DE ERVA',
    'boss5j.name': 'O BUGREIRO',
    'boss5a.name': 'A BOIGUAÇU',
    'boss5b.name': 'A BOITATÁ',

    /* falas ao passar */
    'b5.pasture': 'O potreiro do pai... Os bois tão de pé, olhando pra mim. Mas não têm olho nenhum.',
    'b5.fence': 'A cerca tá arrebentada. O gado fugiu morro acima, atrás de alguma luz.',
    'b5.erva': 'Ervateira Becker, desde 1889. Passei a vida lendo essa placa e nunca perguntei por quê.',
    'b5.forest': 'O povo chama isso aqui de Morro dos Bugres. Depois de hoje, eu não chamo mais.',
    'b5.village': 'Buracos redondos no chão, cobertos de capim... Isso aqui era uma aldeia.',
    'b5.village2': 'As casas eram debaixo da terra, pro frio não entrar. Na escola ninguém me contou isso.',
    'b5.mouth': 'A boca da caverna. E tem alguém esperando lá na frente, com uma tocha.',
    'b5.cave': 'Olhos... A parede inteira tá cheia de olhos. E todos olhando pra mim.',
    'b5.treasure': 'Os postes de Teewald. Lampiões, as velas da igreja, a estrela da fábrica. Tudo o que tinha luz.',
    'b5.truck': '...O meu caminhão.',

    /* placas */
    's5.linha': 'POTREIRO BECKER — LINHA BECKER\n"Feche a porteira."\n(Ela está escancarada.)',
    's5.erva': 'ERVATEIRA BECKER — DESDE 1889\nErva sapecada no carijó.\nA placa caiu, comida pelo cupim.',
    's5.gralha': 'NÃO CORTE O PINHEIRO.\nRiscado a canivete: "A gralha-azul enterra\no pinhão e esquece onde. Assim nasce a mata."',
    's5.stone': 'Gravuras na pedra: círculos, pontos,\npegadas de passarinho. Mais velhas\nque qualquer cruz de Teewald.',
    's5.cavesign': 'CAVERNA DOS BUGRES — PONTO TURÍSTICO\nPrefeitura de Teewald, 1950.\n"Bugre" era o nome feio dado aos Kaingang.',
    's5.candles': 'Velas da Matriz, ainda com a fita\nda primeira comunhão. A cobra\nlevou até isso.',

    /* o bugreiro */
    'c5.j1': 'Tu tem a cara dos Becker, guri.',
    'c5.j2': 'Quem é tu?',
    'c5.j3': 'Jacob Becker. Em oitenta e oito eu limpei esse morro. A ervateira saiu do meu trabalho.',
    'c5.j4': 'O avô do meu pai... O bugreiro.',
    'c5.j5': 'Volta pra casa. Ninguém vai acender fogo nenhum nessa caverna.',
    'c5.j6': 'Então sai da frente, bisavô.',
    'c5.j7': 'Terra de ninguém. Eu só limpei o mato.',
    'c5.j7b': 'Tinha gente nesse mato.',
    'c5.j8': '...não deixa... acenderem o fogo...',
    'c5.j9': 'Descansa, Jacob. Hoje o fogo volta pra quem sempre cuidou dele.',

    /* o fogo na boca da caverna */
    'c5.c1': 'Guri! Tu tá inteiro?',
    'c5.c2': 'Tô, pai. Era o teu avô. O Jacob.',
    'c5.c3': 'O pai dizia que o velho Jacob nunca mais dormiu uma noite inteira. Agora eu sei por quê.',
    'c5.c4': 'Agora deixa eu fazer o que a minha avó fazia. Nó de pinho queima a noite toda.',
    'c5.cpray': '(Dona Rosa reza na língua dela.)',
    'c5.c5': 'Enquanto esse fogo queimar, a noite não sai da caverna. Vai, guri.',
    'c5.c6': 'Se ela abrir os olhos, tu fecha os teus. E não corre.',
    'c5.c7': 'Vai na frente. Eu fico com elas até o fogo pegar bem.',

    /* a cobra */
    'c5.k1': 'Então é tu que tá comendo a luz de Teewald.',
    'c5.k2': '"Não corre e não olha." Bah, Dona Rosa... fácil falar.',
    'c5.k3': 'Ela engoliu o tesouro inteiro... e furou o teto do morro!',
    'c5.k4': 'Guri! O caminhão pega no tranco, morro abaixo! Eu dirijo, tu segura ela!',
    'c5.k5': 'Bora, pai!',
    'c5.r1': 'Segura firme! Ela vem atrás da gente, acesa feito um poste!',
    'c5.r2': 'Sem a luz dela, o caminhão é só um caminhão. Pisa fundo, pai!',
    'c5.v1': 'Olha, pai... Ela tá subindo.',
    'c5.v2': 'Tá indo atrás do sol. O maior olho de todos.',

    /* prólogo */
    'ch5.card1': 'Teewald City — o dia seguinte',
    'ch5.card2': 'A praça da Matriz, ao entardecer',
    'p5.radio': '...ksshh... 104,5... a estrela da Morgenstern amanheceu apagada... ksshh... e na Linha Becker, mais gado sem os olhos. A prefeitura pede que ninguém suba o Morro dos Bugres...',
    'p5.1': 'Dona Rosa! A gente procurou a senhora o dia todo. Vinte anos, e no mesmo banco!',
    'p5.2': 'Fui buscar nó de pinho no mato. Eu tava aqui antes da praça, Ewald Becker. E vou tá depois.',
    'p5.3': 'A Rosa sabe o que tá comendo os olhos do gado. Senta, Arno. Escuta.',
    'p5.4': 'Vocês chamam de Caverna dos Bugres. Bugre era o nome feio que os colonos davam pra nós, os Kaingang.',
    'p5.l1': 'Antes do navio de vocês, esse morro era nosso. Na boca da caverna a gente mantinha um fogo de nó de pinho.',
    'p5.l2': 'Nas noites compridas o fogo não apagava. Porque lá dentro dorme a Boiguaçu, a cobra grande.',
    'p5.l3': 'Uma vez a noite não acabou. Choveu dias e dias, e os bichos morreram no escuro.',
    'p5.l4': 'A cobra acordou com fome e comeu os olhos dos bichos mortos. De tanto comer luz, ficou toda acesa.',
    'p5.l5': 'Virou a boitatá, a cobra de fogo. Quem olha pra ela fica cego.',
    'p5.l6': 'Quando o navio de vocês chegou, veio junto o Antigo.',
    'p5.l7': 'A minha avó, que era kujà, e a tua bisavó Hedwig, Frida, amarraram ele no Pinheiro Velho. Juntas.',
    'p5.l8': 'A Oma Hedwig nunca contou isso.',
    'p5.l9': 'Muita coisa ninguém contou.',
    'p5.l10': 'Em 1888, um Becker pagou os bugreiros pra limpar o morro. Chegaram de madrugada na caverna.',
    'p5.l11': 'O fogo apagou naquela noite.',
    'p5.l12': 'Jacob Becker... o meu avô.',
    'p5.l13': 'No ano seguinte abriram a ervateira em cima da nossa terra.',
    'p5.5': 'Cinco meses de noite acordaram a cobra. Ela comeu os olhos do gado, a luz dos postes...',
    'p5.5b': '...e o teu caminhão, Becker.',
    'p5.6': 'Na noite em que eu cheguei... vinham dois faróis na minha mão, no meio da cerração. Eu desviei.',
    'p5.7': 'Não tinha carro nenhum.',
    'p5.8': 'Eram os olhos dela. Quem olha a boitatá fica cego.',
    'p5.9': 'Se tu ver a boitatá, não corre e não olha. Fecha os olhos e fica quieto, que ela passa.',
    'p5.10': 'Eu e a Frida vamos acender o fogo na boca da caverna. Tu sobe e traz o teu caminhão de volta.',
    'p5.11': 'Dessa vez eu vou junto.',
    'p5.12': 'Bah. Então vamos, pai. Antes que escureça de vez.',

    /* final */
    'e5.1': 'Ela tá indo engolir o sol...',
    'e5.2': 'O maior olho de todos. Gulosa até o fim.',
    'e5.3': 'Vaga-lumes... Mil vaga-lumes.',
    'e5.4': 'Olha lá embaixo, guri. Os postes de Teewald, acendendo um por um.',
    'e5.5': 'A Noite Grande acabou. Mas agora o fogo é de vocês também. Todo inverno.',
    'e5.6': 'Todo inverno, Dona Rosa. A gente acende junto.',
    'e5.7': 'Mas a cerração não foi embora. Olhem lá.',
    'e5.8': 'Tá descendo a serra feito um rio, pras linhas do interior.',
    'e5.r1': '...ksshh... 104,5... na Linha Esperança, três crianças sumiram de madrugada... ksshh... testemunhas falam de um vulto coberto de barba-de-velho, com um saco nas costas...',
    'e5.9': 'Linha Esperança. A primeira picada de 1852.',
    'e5.cap': 'O fogo do morro voltou a queimar.',
    'end5.chapter': 'FIM DO CAPÍTULO 5',
    'end5.next': 'Capítulo 6: A Noite do Pelznickel',
    'cred5.2': 'Capítulo 5 — A Noite Grande',
    'cred5.3': 'Lendas, gente e lugares',
    'cred5.4': 'a boiguaçu e a boitatá, a cobra de fogo,',
    'cred5.5': 'o pinhão, a gralha-azul e o nó de pinho,',
    'cred5.6': 'as casas subterrâneas dos Kaingang.',
    'cred5.7': 'Em memória dos Kaingang,',
    'cred5.8': 'que estavam aqui antes de todos.'
  });

  Object.assign(L.en, {
    'chap.5': '5 — THE GREAT NIGHT',
    'chap.5.d': 'Headlights climb the Morro dos Bugres. Up there, something is eating the light.',
    'stage5.num': 'STAGE 5',
    'stage5.name': 'THE GREAT NIGHT',
    'mission5': 'Climb the hill to the cave and bring your truck back. If the eyes open, close yours.',

    'hint.c5cover': 'HOLD ↓: CLOSE YOUR EYES!',
    'hint.c5cover@touch': 'HOLD ↓ ON THE D-PAD: CLOSE YOUR EYES!',
    'hint.c5stuck': 'ITS HEAD IS STUCK IN THE GROUND: HIT IT NOW!',
    'hint.c5spit': 'KNOCK THE EYES DOWN WITH PUNCHES OR BULLETS!',
    'hint.c5bite': 'ITS HEAD IS STUCK IN THE PLANKS: PUNCH IT!',
    'hint.c5cones': 'GET OUT FROM UNDER THE SHADOWS!',
    'hint.c5beam': 'HIGH BEAMS! IT SWALLOWS THE LIGHT AND GETS DIZZY!',
    'hint.c5pinha': 'FALLING PINE CONES: STEP OUT OF THE SHADOW!',
    'hint.c5jacob': 'DODGE THE AIM!  JUMP THE CHARGE!  AVOID FIRE!',
    'hint.c5boss1': 'WHEN ITS HEAD HITS THE GROUND, ATTACK!',
    'hint.c5road': 'HIT THE HEAD WHEN IT BITES OR GETS DIZZY!',
    'c5.oxcalm': 'CALMED DOWN',
    'c5.whistle': '(whistle)',
    'c5.hard': 'GLANCING BLOW!',
    'c5.hard2': 'GLANCING BLOW!',
    'c5.eyes': 'THE EYES!',
    'c5.dazzled': 'DAZZLED...',
    'c5.dazzle': 'DAZZLED!',
    'c5.safe': 'PHEW...',
    'c5.curve': 'CURVE!',
    'c5.curve2': 'HOLD ON, SON!',
    'c5.beam': 'HIGH BEAMS!',
    'c5.firecp': 'FIRE LIT',
    'item.pinhao': 'BOILED PINE NUTS',
    'en.c5ox': 'EYELESS OX',
    'en.c5dog': 'HUNTER\'S HOUND',
    'en.c5erv': 'MATE WORKER',
    'en.c5eye': 'FLYING EYE',
    'en.c5orb': 'EYE',
    'en.c5bale': 'HAY BALE',
    'en.c5raido': 'MATE SACK',
    'boss5j.name': 'THE BUGREIRO',
    'boss5a.name': 'THE BOIGUAÇU',
    'boss5b.name': 'THE BOITATÁ',

    'b5.pasture': 'Dad\'s pasture... The cattle are standing there, staring at me. But they have no eyes.',
    'b5.fence': 'The fence is torn down. The herd ran up the hill, chasing some light.',
    'b5.erva': 'Becker Mate Plantation, since 1889. I read that sign my whole life and never asked why.',
    'b5.forest': 'Folks call this the Morro dos Bugres. After tonight, I won\'t call it that anymore.',
    'b5.village': 'Round holes in the ground, covered with grass... This was a village.',
    'b5.village2': 'The houses were dug into the earth, to keep the cold out. Nobody at school ever told me.',
    'b5.mouth': 'The mouth of the cave. And someone is waiting up ahead, with a torch.',
    'b5.cave': 'Eyes... The whole wall is covered in eyes. And all of them are looking at me.',
    'b5.treasure': 'Teewald\'s street lamps. Lanterns, the church candles, the factory star. Everything that had light.',
    'b5.truck': '...My truck.',

    's5.linha': 'BECKER PASTURE — LINHA BECKER\n"Close the gate."\n(It is wide open.)',
    's5.erva': 'BECKER MATE PLANTATION — SINCE 1889\nMate toasted over the carijó fire.\nThe sign has fallen, eaten by termites.',
    's5.gralha': 'DO NOT CUT THE PINE.\nCarved below: "The azure jay buries the pine\nnut and forgets where. So the forest grows."',
    's5.stone': 'Carvings in the stone: circles, dots,\nbird tracks. Older than any cross\nin Teewald.',
    's5.cavesign': 'CAVERNA DOS BUGRES — TOURIST SITE\nTeewald Town Hall, 1950.\n"Bugre" was the ugly name given to the Kaingang.',
    's5.candles': 'Candles from the parish church, still\ntied with first-communion ribbons.\nThe snake took even those.',

    'c5.j1': 'You\'ve got the Becker face, boy.',
    'c5.j2': 'Who are you?',
    'c5.j3': 'Jacob Becker. In eighty-eight I cleared this hill. The mate plantation came from my work.',
    'c5.j4': 'My father\'s grandfather... The bugreiro.',
    'c5.j5': 'Go home. Nobody is lighting any fire in this cave.',
    'c5.j6': 'Then get out of my way, great-grandpa.',
    'c5.j7': 'No man\'s land. All I did was clear the brush.',
    'c5.j7b': 'There were people in that brush.',
    'c5.j8': '...don\'t let them... light the fire...',
    'c5.j9': 'Rest, Jacob. Tonight the fire goes back to the ones who always kept it.',

    'c5.c1': 'Son! Are you all right?',
    'c5.c2': 'I\'m fine, Dad. It was your grandfather. Jacob.',
    'c5.c3': 'My father said old Jacob never slept a whole night again. Now I know why.',
    'c5.c4': 'Now let me do what my grandmother used to do. Pine knots burn all night long.',
    'c5.cpray': '(Dona Rosa prays in her own language.)',
    'c5.c5': 'As long as this fire burns, the night can\'t leave the cave. Go, son.',
    'c5.c6': 'If it opens its eyes, you close yours. And don\'t run.',
    'c5.c7': 'Go ahead. I\'ll stay with them until the fire catches.',

    'c5.k1': 'So you\'re the one eating Teewald\'s light.',
    'c5.k2': '"Don\'t run and don\'t look." Easy for you to say, Dona Rosa.',
    'c5.k3': 'It swallowed the whole treasure... and broke through the hill!',
    'c5.k4': 'Son! The truck will bump-start, downhill! I\'ll drive, you hold it off!',
    'c5.k5': 'Let\'s go, Dad!',
    'c5.r1': 'Hold on tight! It\'s coming after us, lit up like a lamp post!',
    'c5.r2': 'Without its light, the truck is just a truck. Floor it, Dad!',
    'c5.v1': 'Look, Dad... It\'s going up.',
    'c5.v2': 'It\'s going after the sun. The biggest eye of all.',

    'ch5.card1': 'Teewald City — the next day',
    'ch5.card2': 'The parish square, at dusk',
    'p5.radio': '...kssh... 104.5... the Morgenstern star went dark overnight... kssh... and on Linha Becker, more cattle without eyes. Town hall asks that nobody climb the Morro dos Bugres...',
    'p5.1': 'Dona Rosa! We looked for you all day. Twenty years, and the same bench!',
    'p5.2': 'I went to gather pine knots. I was here before the square, Ewald Becker. And I\'ll be here after it.',
    'p5.3': 'Rosa knows what\'s eating the cattle\'s eyes. Sit down, Arno. Listen.',
    'p5.4': 'You call it the Caverna dos Bugres. Bugre was the ugly name the settlers gave us, the Kaingang.',
    'p5.l1': 'Before your ship came, this hill was ours. At the mouth of the cave we kept a fire of pine knots.',
    'p5.l2': 'On long nights the fire never went out. Because inside sleeps the Boiguaçu, the great snake.',
    'p5.l3': 'Once, the night did not end. It rained for days, and the animals died in the dark.',
    'p5.l4': 'The snake woke up hungry and ate the eyes of the dead animals. It ate so much light it began to glow.',
    'p5.l5': 'It became the boitatá, the fire snake. Whoever looks at it goes blind.',
    'p5.l6': 'When your ship arrived, the Old One came with it.',
    'p5.l7': 'My grandmother, who was a kujà, and your great-grandmother Hedwig, Frida, bound him to the Old Pine. Together.',
    'p5.l8': 'Oma Hedwig never told that part.',
    'p5.l9': 'There\'s a lot nobody told.',
    'p5.l10': 'In 1888, a Becker paid the bugreiros to clear the hill. They reached the cave before dawn.',
    'p5.l11': 'The fire went out that night.',
    'p5.l12': 'Jacob Becker... my grandfather.',
    'p5.l13': 'The next year they opened the mate plantation on top of our land.',
    'p5.5': 'Five months of night woke the snake. It ate the cattle\'s eyes, the street lights...',
    'p5.5b': '...and your truck, Becker.',
    'p5.6': 'The night I came back... two headlights were coming at me, in the fog. I swerved.',
    'p5.7': 'There was no car.',
    'p5.8': 'Those were its eyes. Whoever looks at the boitatá goes blind.',
    'p5.9': 'If you see the boitatá, don\'t run and don\'t look. Close your eyes and keep still, and it will pass.',
    'p5.10': 'Frida and I will light the fire at the mouth of the cave. You climb up and bring your truck back.',
    'p5.11': 'This time I\'m coming with you.',
    'p5.12': 'Then let\'s go, Dad. Before it gets dark for good.',

    'e5.1': 'It\'s going to swallow the sun...',
    'e5.2': 'The biggest eye of all. Greedy to the very end.',
    'e5.3': 'Fireflies... A thousand fireflies.',
    'e5.4': 'Look down there, son. Teewald\'s street lights, coming on one by one.',
    'e5.5': 'The Great Night is over. But now the fire is yours too. Every winter.',
    'e5.6': 'Every winter, Dona Rosa. We\'ll light it together.',
    'e5.7': 'But the fog hasn\'t gone. Look there.',
    'e5.8': 'It\'s flowing down the mountain like a river, into the farm lines.',
    'e5.r1': '...kssh... 104.5... on Linha Esperança, three children vanished before dawn... kssh... witnesses describe a figure covered in old man\'s beard, with a sack on its back...',
    'e5.9': 'Linha Esperança. The first trail cut through the forest in 1852.',
    'e5.cap': 'The fire on the hill burns again.',
    'end5.chapter': 'END OF CHAPTER 5',
    'end5.next': 'Chapter 6: The Night of the Pelznickel',
    'cred5.2': 'Chapter 5 — The Great Night',
    'cred5.3': 'Legends, people and places',
    'cred5.4': 'the boiguaçu and the boitatá, the fire snake,',
    'cred5.5': 'pine nuts, the azure jay and the pine-knot fire,',
    'cred5.6': 'the underground houses of the Kaingang.',
    'cred5.7': 'In memory of the Kaingang,',
    'cred5.8': 'who were here before anyone else.'
  });
})();
